- src/modules/skinManager/src/SkinDiagnosticsReadThread.cpp
This PR addresses the following minor issues:
1. Fix Windows-specific compile warnings on VS as raised by @pattacini [here](https://github.com/robotology/icub-main/pull/17#issuecomment-69559068)
2. Use bitwise operation to advance to next error mask as suggested by @barbalberto [here](https://github.com/robotology/icub-main/pull/17#issuecomment-69575499)
@barbalberto Please do test these, since I have no more access to the robot.
Also @barbalberto @pattacini @lornat75 , I insist on removing [the definition file for skin error codes](https://github.com/robotology/icub-main/blob/master/src/libraries/icubmod/motionControlLib/skinDiagnostic.h) from `src/libraries/icubmod/motionControlLib`. It has **really** nothing to do there. Moreover, the global include `#include <skinDiagnostic.h>` …
> Skin Diagnostics clean-up

- src/libraries/icubmod/cfw2Can/Cfw2Can.cpp
- src/libraries/icubmod/cfw2Can/Cfw2Can.h
Rationale: `dynamic_cast` has a runtime overhead that we pay for each copied Cfw2CanMessage (rough estimate ~1% of CPU in pc104 use of robotInterface). 
Nobody is currently testing the success of this dynamic_cast by checking the `std::bad_cast` exception, so if it will ever fail both the dynamic_cast and the static_cast will cause a crash (however, I don't think this is possible with the current source base). 
I already tested this on the real robot, but given that this is a critical piece of code is better to review this change appropriately. 
cc @lornat75 @randaz81 @francesco-romano
> [icubmod] dynamic_cast -> reinterpret_cast in Cfw2CanMessage::operator=

- src/tools/stereoCalib/include/stereoCalibThread.h
- src/tools/stereoCalib/src/stereoCalibThread.cpp
- added cofiguration flag to specify pattern used (boardType) - default to CHESSBOARD
- allowed cv::findCirclesGridDefault to run when boardType is CIRCLES_GRID or ASYMMETRIC_CIRCLES_GRID
- added new calculation for calcChessboardCorners for ASYMMETRIC_CIRCLES_GRID
- added calls to cout flush due to text not always being printed
- added an early exit of threadInit when only doing MonoCalibration to remove dependence on robot joint positions when they are not used. This allows MonoCalibration to work when not running on a robot
- bug fix: changed flag options when calling cv::findChessboardCorners to use | instead of & when multiple flags are specified
> added (asymmetric) circles in  stereoCalib

- src/libraries/icubmod/canBusAnalogSensor/CanBusAnalogSensor.cpp
- src/libraries/icubmod/canBusAnalogSensor/CanBusAnalogSensor.h
Instead of always sending OK status, even if a proper status is set in the run method.
I could push directly to master, but I am opening the PR just to be sure with @randaz81 we are not breaking anything by changing this "always return OK" behaviour.
> [CanBusAnalogSensor] properly return device status

- app/robots/iCubDarmstadt01/hardware/motorControl/left_lower_leg-ems7-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/left_upper_arm-ems1-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/left_upper_leg-ems6-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/right_lower_leg-ems9-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/right_upper_arm-ems3-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/right_upper_leg-ems8-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/torso-ems5-mc.xml
- app/robots/iCubGenova02/hardware/motorControl/left_upper_arm-ems1-mc.xml
- app/robots/iCubGenova02/hardware/motorControl/right_upper_arm-ems3-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/left_lower_leg-ems7-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/left_upper_arm-ems1-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/left_upper_leg-ems6-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/right_lower_leg-ems9-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/right_upper_arm-ems3-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/right_upper_leg-ems8-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/torso-ems5-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/left_lower_leg-ems7-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/left_upper_leg-ems6-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/right_lower_leg-ems9-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/right_upper_leg-ems8-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/torso-ems5-mc.xml
- app/robots/iCubSheffield01/hardware/motorControl/left_upper_arm-ems1-mc.xml
- app/robots/iCubSheffield01/hardware/motorControl/right_upper_arm-ems3-mc.xml
- app/robots/iCubSheffield01/hardware/motorControl/torso-ems5-mc.xml
affected robots:
iCubGenova02
iCubGenova04
iCubDarmstadt01
iCubSheffield01
iCubHeidelberg01
> updated ETH robot configuration files to use metric units in position control

- src/modules/actionsRenderingEngine/src/VisuoThread.cpp
- src/modules/templatePFTracker/src/particleFilter.cpp
- `cvCopy()` takes over `cvCopyImage()`
- `cvSplit()` takes over `cvCvtPixToPlane()`
Hopefully, these changes are back-compatible.
> compatibility with opencv 3.0.0

- app/iCubCluster/scripts/icub-cluster-run.sh
- app/iCubCluster/scripts/icub-cluster-server.sh
Fix for https://github.com/robotology/icub-main/issues/154
Works fine on our setup, and has the advantage that `LD_LIBRARY_PATH` does not need to be set, if `INSTALL_WITH_RPATH` is used.
Best, Tobias
> Do not copy yarprun / yarpserver in /tmp

- app/iCubCluster/scripts/icub-cluster.py
Takes the actual value of the `User` and `Nameserver node` into account, and makes the other fields `readonly` such that no confusion caused.
> Fix https://github.com/robotology/icub-main/issues/168

- app/iCubCluster/scripts/icub-cluster.py
Hi,
previously it wasn't possible to set a `user`, but not the `display` in icub-cluster.py.
This PR extends the script accordingly.
I would appreciate if you merge this PR.
Best,
Tobias
> Proper handling of display in icub-cluster.py

- src/libraries/icubmod/embObjLib/usrcbk/embObjLib_mngmnt_callback.c
Now it is easier to understand which CAN boards are missing because robotInterface parses the diagnostics messages coming from ETH boards and prints them in human readable form.
> candiscovery diagnostics

- conf/iCubOptions.cmake
Add support for compiling the libraries in icub-main as shared libraries, using the new feature of cmake 3.4 `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` .
See http://www.kitware.com/blog/home/post/939 for more info on this feature.
This enables the `ICUB_SHARED_LIBRARY` option on Windows with CMake >= 3.4 , but  its default value remains OFF.
> [cmake][msvc] (optional) support for producing shared libraries (dll)

- src/libraries/icubmod/analogServer/analogServer.cpp
- src/libraries/icubmod/skinWrapper/skinWrapper.cpp
Introduced changes:
- closing skin ports that were remaining open : close function is now called inside threadRelease function
- threadRelease is  now called  only by RateThread, whereas before it was called twice
> fixed bug on Skin ports issue #235

- src/libraries/ctrlLib/CMakeLists.txt
- src/libraries/ctrlLib/include/iCub/ctrl/math.h
- src/libraries/iKin/CMakeLists.txt
- src/modules/camCalibWithPose/CMakeLists.txt
- src/simulators/iCubSimulation/CMakeLists.txt
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
- src/tools/iCubGui/src/CMakeLists.txt
- src/tools/iCubGui/src/mesh.h
As discussed in https://github.com/robotology/QA/issues/81, **`ctrlLib`** now depends on **`cmath`** to import mathematical constants (e.g. `M_PI`) instead of re-defining them from scratch.
This dependency is then published by means of suitable cmake macro for systems using **MSVC** compilers. In this respect, I have explicitly avoided referring to corresponding Cmake versions in order not to retain some unnecessary leftover in Windows (as said, Windows users have more recent versions of Cmake). Let's see if this will suffice.
I've also given a go to the compilation of `wysiwyd`, `karma` and `iol` sister repositories without any problem related to this specific change.
/cc @traversaro
> ctrlLib inherits math constants from cmath and publish them with cmake

- src/libraries/ctrlLib/CMakeLists.txt
- src/libraries/ctrlLib/include/iCub/ctrl/math.h
- src/libraries/ctrlLib/src/math.cpp
- src/libraries/iDyn/CMakeLists.txt
- src/libraries/iDyn/include/iCub/iDyn/iDyn.h
- src/libraries/iDyn/src/iDyn.cpp
- src/libraries/iKin/CMakeLists.txt
- src/libraries/iKin/include/iCub/iKin/iKinFwd.h
- src/libraries/optimization/CMakeLists.txt
- src/libraries/optimization/src/calibReference.cpp
- src/modules/camCalibWithPose/CMakeLists.txt
- src/modules/iKinGazeCtrl/CMakeLists.txt
- src/modules/wholeBodyDynamics/CMakeLists.txt
- src/modules/wholeBodyDynamics/observerThread.cpp
- src/simulators/iCubSimulation/CMakeLists.txt
- src/tools/depth2kin/CMakeLists.txt
- src/tools/depth2kin/src/nlp.cpp
- src/tools/iCubGui/src/CMakeLists.txt
- src/tools/stereoCalib/src/stereoCalibThread.cpp
Following up discussions in https://github.com/robotology/QA/issues/81, `ctrlLib` declares now math symbols within its own namespace to avoid referring explicitly to e.g. `M_PI` in the public headers.
To get `icub-main` compiled I had to apply changes here and there. I'm afraid that this new approach will have an impact on sister projects: I think it is no longer guaranteed that they'll compile smoothly.
> ctrlLib defines math symbols to avoid referring to M_PI in the headers

- src/libraries/icubmod/cfw2Can/Cfw2Can.cpp
- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.h
These changes have been made in response to issue #268. As indicated by @traversaro the bug is the result of `yarp` commit https://github.com/robotology/yarp/commit/31bdd9ab4f8cc9a2e0e9089afffdfc67b6159f69 
It is totally possible that other files that compile only on the pc104 may be affected by this change in `yarp` but I have no way of testing this.
> Include Value.h after yarp commit removing Value.h from Bottle.h

- conf/iCubExportBuildTree.cmake
- conf/iCubExportForInstall.cmake
Before this change, icub-main polluted the CMake cache of all
the downstream projects with fake "options" such as ICUB_USE_GSL,
ICUB_USE_OpenCV, etc . This flags appeared as editable options in ccmake
or cmake-gui of the downstream projects, causing confusion among the users.
With this change the dependency flags are still exposed to the downstream
projects, but without polluting the cache, as done in YARP
(see https://github.com/robotology/yarp/blob/6598fc3d643b334b1afd312acf4734c5d3eb8d1e/conf/template/YARPConfig.cmake.in#L89 )
An additional unset(ICUB_USE_**) is added to clean the existing caches of downstream projects.
> [cmake] Do not pollute cache of downstream projects

- conf/iCubExportBuildTree.cmake
- conf/iCubExportForInstall.cmake
I noticed that the include_DIRS were still polluting the cmake cache.
Some trailing whitespace cleaning done in the meanwhile, PR without whitespaces changes available at `https://github.com/robotology/icub-main/pull/280?w=1` .
Just a duplication of https://github.com/robotology/icub-main/pull/267 , if nobody has nothing to comment I will merge it this evening.
> [cmake] Do not pollute cache of downstream projects part 2

- src/modules/dualCamCalib/include/iCub/DualCamCalibModule.h
- src/modules/dualCamCalib/src/DualCamCalibModule.cpp
- src/tools/CMakeLists.txt
- src/tools/imageSplitter/CMakeLists.txt
- src/tools/imageSplitter/include/imageSplitter.h
- src/tools/imageSplitter/src/imageSplitter.cpp
- src/tools/imageSplitter/src/main.cpp
Modified dualCamCalib to accept a dual image as an input (also fix a segfault).
Add imageSplitter module to split a dual image (either verically or horizontally aligned) into left and right single frames.
> Dual calib dual image

- app/iCubCluster/conf/cluster-config.xml
- app/iCubCluster/scripts/icub-cluster-server.sh
- app/iCubCluster/scripts/icub-cluster.py
* iCubCluster: Remove unused "type" option and references to yarpserver3. The "type" option is actually unused, and yarpserver3 will be soon removed from yarp (see robotology/yarp#780)
* icub-cluster-server.sh: Use memory instead /tmp for yarpserver portdb and and subdb. Memory should be faster. @lornat75 What do you think about this change?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225122399%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225350502%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225362462%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/p …
> iCubCluster

- app/skinGui/conf/skinGui/torso.ini
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/354%23issuecomment-226715007%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/354%23issuecomment-227147991%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/354%23issuecomment-228001178%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/354%23issuecomment-226715007%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40matejhof%20could%20you%20have%20a%20look%20at%20this%20PR%3F%22%2C%20%22created_at%22%3A%20%222016-06-17T08%3A46%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A% …
> fixed triangle number 52 orientation in iCubSkinGui

- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.cpp
- src/libraries/icubmod/dragonfly2/winnt/FirewireCameraDC1394-DR2_2.cpp
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' height=40></a>
<a href='https://www.codereviewhub.com/robotology/icub-main/pull/359?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/359'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a href='#crh-end'></a>
> DragonFly2: change error message to info since it is not an error

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
In this branch, following changes have been done about embObjMotionControl:
1- bug fixed in GetReftorueRaw. Now it returns Torque Pid's reference even if joint is in compliant mode.
2- Removed use of TorueCh, TorqueId and TorqueMax (xml parameters)
3- Now the device sends torque values expressed in microNm to firmware. For this reason it is necessary the corresponding firmware and therefore I needed to increment Motion Control protocol version and firmware-shared-version in cmake  file.
> Stiff damp float

- src/libraries/icubmod/embObjLib/CMakeLists.txt
This fixes the segmentation fault at the end of `yarprobotinterface`, `yarpdev --list` and `yarp plugin --all` when more that one *embObj* device is enabled.
When the shared library is built static and linked to a plugin, all the symbols of the library are exported in the plugin. When 2 plugins are loaded at the same time, there is a symbol conflict and only the functions from one of those are called. This is ok but when the library is closed, a segmentation fault is generated, probably on some singleton/static object.
Hiding the symbols with `-fvisibility=hidden` is not ok though, because each plugin will have its own version of the singleton and therefore the second plugin loaded will not be able to create it and to bind to the ip port.
Since this library contains a singleton, and since …
> Create ethResources library as shared

- app/iCubCluster/scripts/icub-cluster.py
@pattacini Using the latest version of the icub cluster I get 
...
||| found /exports/code/icub-main/build/share/iCub/contexts/iCubCluster
||| checking [/exports/code/icub-main/build/share/iCub/contexts/iCubCluster/icub-cluster-icon.png] (context)
||| found /exports/code/icub-main/build/share/iCub/contexts/iCubCluster/icub-cluster-icon.png
||| finding file [from]
Traceback (most recent call last):
File "/home/icub/software_shared/icub-main/build/bin/icub-cluster.py", line 523, in <module>
newNode=Node(node.firstChild.data, False, "", user, ssh_options)
NameError: name 'ssh_options' is not defined.
I think that the ssh_options are indented to be empty if the node has no attributes. Setting the string to empty fixes my problem but I am not sure if that should be a global fix or it only …
> iCubCluster ssh settings fix

- src/libraries/skinDynLib/include/iCub/skinDynLib/skinPart.h
- src/libraries/skinDynLib/src/skinPart.cpp
- enhancing `skinDynLib` with skin part version ("V1" / "V2" ...). N.B. For skin parts that to my knowledge have only one version, like torso, I set it to "V1".
- fixing spatial_sampling variable -> "triangle" instead of "patch"
- some improved comments
@alecive please have a look.
maybe also @traversaro
> adding skin part version information

- src/libraries/iKin/ChangeLog
- src/libraries/iKin/include/iCub/iKin/iKinFwd.h
- src/libraries/iKin/src/iKinFwd.cpp
- src/modules/iKinGazeCtrl/include/iCub/utils.h
- src/modules/iKinGazeCtrl/src/controller.cpp
- src/modules/iKinGazeCtrl/src/localizer.cpp
- src/modules/iKinGazeCtrl/src/main.cpp
- src/modules/iKinGazeCtrl/src/solver.cpp
- src/modules/iKinGazeCtrl/src/utils.cpp
Following up discussion in #285, I've prepared these changes to:
1. Update `iKin` to deal with new kinematic structures (the so-called version `2.5`).
2. Streamline `iKinGazeCtrl` to the use of new command-line parameters `--head_version` in place of `--headV2`.
In the new context of diverse head versions, `--headV2` was quite limiting, also considering future hardware releases.
I'm going to create a corresponding PR in [**robots-configuration**](https://github.com/robotology/robots-configuration) to update `iKinGazeCtrl` parameters.
Once done, I'll send around an announcement.
@traversaro could you please have a look here?
> Code to address iCub Head v2.5

- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
Fix enum name typo in yarp triggered update in icub's device using it.
> V4L camera: fix enum name after typo fix in yarp

- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
Fix common error in `checkMotionDone`.
That function returns a single value even when asked for more than one joint.
> iCub_Sim: fix error in checkMotionDone

- src/modules/actionsRenderingEngine/include/iCub/MotorThread.h
- src/modules/actionsRenderingEngine/src/MotorThread.cpp
The way **actionsRenderingEngine** (ARE) is currently homing the gaze is somewhat mazy. The `goHome()` method triggers homing by changing the state of a internal variable which in turn is handled within `run()`.
Instead, this PR brings everything inside `goHome()`.
> Better handling of homing gaze in ARE

- .travis.yml
- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
We found and fixed a memory leak triggered when you open two devices `usbCamera`.
> V4L_camera: fix potential memory leak

- src/tools/frameGrabberGui2-qt/loadingwidget.cpp
Fix the following valgrind error get opening FrameGrabber gui:
```
==30575== Conditional jump or move depends on uninitialised value(s)
==30575==    at 0x6666225: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x66683FF: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x66699A2: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x6669F0B: QResource::isCompressed() const (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x666A1EE: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x669ECCF: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x669EE6B: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1)
==30575==    by 0x663DA9E: QFileInfo::QFileInfo(QString …
```
> frameGrabberGui: fixing valgrind error, int uninitialised

- src/tools/imageSplitter/src/imageSplitter.cpp
This PR changes the default behaviour of imageSplitter, if nothing is specified it connects to `remote` once it is launched, otherwise if `connectLater` is set it waits that the connection is made "outside" the module.
> ImageSplitter: changing the logic of the connection to the source port

- app/default/scripts/cameras_calib.xml.template
- app/default/scripts/cameras_calib_bayer_320_240.xml.template
- app/default/scripts/cameras_calib_bayer_640_480.xml.template
This PR update the templates for using the new `grabberDual` through `yarpmanager`.
> Update xml template for using the new ServerGrabber

- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
This PR introduce the `-- flip` parameter for flipping the image around the *y axis*, useful for `leopard_python` cameras
TODO:
Ready to be merged.
> usbCamera: add flip parameter for leopard_python camera

- CMakeLists.txt
- src/libraries/icubmod/embObjLib/ethManager.cpp
Referring https://github.com/robotology/yarp/issues/1233, this commit handles the `icub-main` side of the issue.
In short, the macro `ICUB_USE_REALTIME_LINUX` has been removed, and the code that was wrapped by it now is compiled by default on `unix` platforms. The other way was to turn on the advanced CMake variable `ICUB_REALTIME_EXPERIMENTAL`, but since these priorities should always be set, I removed that options and used the `__unix__` macro instead.
@marcoaccame @drdanz @lornat75
> Enable by default the increased thread priority of EthSender and EthReceiver

- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
Previously the rescale did not take into account the form factor (4/3 or 16/9) of the image, so rescaling may led to stretched or compressed images.
This PR fix this error.
Also introduces the possibility to set color settings like saturation from config file or command line which was missing.
> usbCamera: fix rescaling

- src/tools/canLoader/canLoaderLib/downloader.cpp
- src/tools/canLoader/canLoaderLib/downloader.h
- src/tools/canLoader/canLoaderLib/driver.h
Due to a missing return in the implementation of setVerbose function in canLoaderLib, building icub-main on Windows failed (VS2013-64bit).
If there are no reasons for keeping the return value and returning something, please merge the pull request.
> Fix build on Windows

- src/CMakeLists.txt
This is useful to significantly reduce travis compile time for projects that need to compile icub-main.
> Added advanced options to exclude parts of icub-main build.

- app/iCubCluster/CMakeLists.txt
This PR change the destination of the installation of the cluster-config.xml to the `yarpmanager` context, to use the `iCubCluster` integrated in `yarpamanger`.
> iCubCluster: set installation destination to yarpmanager context

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjStrain/embObjStrain.cpp
Added support for discovery of strain2 boards. It requires to update icub-firmware-shared and the FW of ETH boards.
> strain2support

- .travis.yml
Until https://github.com/robotology/homebrew-formulae/issues/12 is fixed, we don't have an easy way to get ipopt on macOS .
> [travis] Do not install ipopt on Homebrew

- bindings/CMakeLists.txt
- bindings/icub.i
This PR fixes issue #302 (which is closed but was never resolved).
It consists of two parts:
1. Allowing to use the bindings with Python3 (code copy/pasted from yarp)
2. The actual fix of the linking problems by removing obsolete include files and replacing them by up-to-date ones.
Full credits to @towardthesea 
A proper cleanup of the bindings should be done in a separate PR.
> Fix issue #302

- .travis.yml
For some reason, commit https://github.com/robotology/icub-main/commit/07016c66032031c15bb5741ec88d460ceedc7ec5 forced the use of yarp master both in icub-main master and devel.
Often changes happening in yarp devel are required for new features arriving in icub-main devel, and pulling yarp master would break the tests (https://github.com/robotology/icub-main/pull/488).
This PR sets Travis in such a way to read the branch using the [`TRAVIS_BRANCH`](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) variable, and sets the correct yarp branch to pull.
This approach allows testing a PR against both yarp master and devel by changing the base branch (editing the PR title and then selecting the target branch).
Edit: after changing the title, just restarting …
> Travis: Pull yarp devel when the branch is devel

- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.cpp
- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.h
- src/tools/frameGrabberGui2-qt/mainwindow.cpp
This PR fixes the following compilation errors:
- `DragonflyDeviceDriver2.cpp`:  error: addition of default argument on redeclaration makes
this constructor a default constructor.
- `framegrabber-gui`: error: no member named 'cout' in namespace 'std' (cherry-picked @drdanz 's commit made on `devel`)
> Fix dragonfly and framegrabber gui compilation errors

- src/tools/frameGrabberGui2-qt/dc1394thread.h
Before, it was included transitively from yarp/dev/RemoteFrameGrabberDC1394.h , 
but that include was removed in https://github.com/robotology/yarp/commit/8950b792f2b1d9d75ebbad041d9effa849c92a6f .
> Include used PolyDriver.h YARP header

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
The checkMotionDone(bool *flags) was recursive because it called itself instaed of checkMotionDoneRaw(int j, bool *flag);
> Bug fixed in checkMotionDone for all joints

- src/tools/focusTool/include/iCubFocusGui.h
iCubFocusTool was incorrectly using remoteFrameGrabber.
Moving the device is yarp broke the compilation.
Fixed instantiating the device as a plugin.
> Fix compilation error in iCubFocusTool

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
Now the device returns the torque value sent  periodically by embedded board.
> EOMC::getTorque() uses remote value instaed of its local cached value

- src/libraries/actionPrimitives/include/iCub/action/actionPrimitives.h
- src/libraries/actionPrimitives/src/actionPrimitives.cpp
- src/libraries/icubmod/cartesianController/ServerCartesianController.cpp
- src/libraries/icubmod/cartesianController/ServerCartesianController.h
- src/modules/actionsRenderingEngine/src/MotorThread.cpp
- src/modules/iKinGazeCtrl/include/iCub/controller.h
- src/modules/iKinGazeCtrl/src/controller.cpp
- src/tools/fingersTuner/main.cpp
Smelling https://github.com/robotology/yarp/issues/1598, I guess change is in the air 😄 
Therefore, I've tried to replace `yarp::sig::VectorOf` with `std::vector` whenever it was possible.
Actually, there's still one place where `yarp::sig::VectorOf` seems necessary:
https://github.com/robotology/icub-main/blob/95de4fd9409c2880a70acbc30c17ac384bc2b615/src/tools/iCubGui/src/objectsthread.h#L188
given that `std::vector` is not portable yet. Perhaps, @ale-git might want to consider refactoring this.
Finally, I've been using `std::vector::data()` meaning that I assume we're fully supporting C++11 as in Yarp, although I don't know whether we'd need to enforce this anywhere in cmake by means of `CMAKE_CXX_STANDARD` option.
cc @drdanz @lornat75 @traversaro
> Limit use of yarp::sig::VectorOf in favor of std::vector

- .gitignore
This PR adds the folder `.vs/` and the json file `CMakeSettings.json` as gitignor entries.
The folder and the file are generated by MS Visual Studio usign CMake projects.
> Add MSVS CMake folder and json in gitignore

- src/tools/ethLoader/ethLoaderLib/CMakeLists.txt
There is a missing `icub_export_library` in `ethLoaderLib` which causes e.g. FirmwareUpdater to fail because the library cannot be found (as it is not being installed).
> Add missing icub_export_library for ethLoaderLib

- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
Using the controlboardWrapper with changes made in function for all joints (https://github.com/robotology/yarp/pull/1668), @Nicogene and I noticed that getTorquesRaw returns false because it was not implemented.
Therefore I implemented it like a for cicle on all joints.
@randaz81 : is there a reason why it was not implemented?
> Implemented CanBusMotionControl::getTorquesRaw

- CMakeLists.txt
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.h
Wait robotology/yarp#1704 before merging
> Fix const correctness

- src/modules/templatePFTracker/src/particleFilter.cpp
Small compilation fix for PFTracker with opencv 3.4
CV_RGB -> cvScalar
it was already defined in 3.2 (https://docs.opencv.org/3.2.0/df/d4e/group__imgproc__c.html) as
` #define CV_RGB(r,  g,  b)   cvScalar( (b), (g), (r), 0 )`   so it should be back compatible
> PFTracker with open_cv 3.4 fix

- bindings/icub.i
- bindings/tests/CMakeLists.txt
- bindings/tests/test_ctrlLib.py
- bindings/tests/test_iKin.py
- bindings/tests/test_load.py
- bindings/tests/test_skinDynLib.py
As title, the `PR` aims to extend the current icub bindings with more icub libraries: skinDynLib, ctrlLib, and provides some test files for `python`: test_load, test_iKin, test_ctrlLib, test_skinDynLib.
I comment out the `iDyn` libraries since nobody really use that libraries :) and I personally don't know how to test if the binding works or not :)
This should work after fixing the binding compilation with @Nicogene 's `PR` https://github.com/robotology/icub-main/pull/541
This is partly to solve the https://github.com/robotology/icub-main/issues/484 issue.
Cheers,
P
@Tobias-Fischer @nunoguedelha @traversaro @drdanz @Nicogene
> Extend icub bindings with icub libraries and tests

- bindings/CMakeLists.txt
- bindings/icub.i
- bindings/tests/CMakeLists.txt
- bindings/tests/test_optimization.py
Following the discussion in https://github.com/robotology/icub-main/issues/484 this wraps most of the optimization library. To make it usable, we need to apply a typemaps for methods that "return" values by reference (not sure whether this also applies to other libraries). I added one example for the calibrate() method (and a test for it). I won't have time (and patience) to wrap all the other methods which pass by reference.
Some notes:
1) Swig 3.0.12 is required (3.0.8 throws some errors when trying to access the data in Python) for the typemap stuff. A check should be added.
2) The typemap currently only checks the parameter types + names, but not the method name. I can't seem to get it to work if I add the method name.
3) There might be a memory leak in the typemap; I'm not sure …
> Wrap optimization library in bindings

- conf/template/icub-config-build-tree.cmake.in
- conf/template/icub-config-install.cmake.in
It was impossible create a cmake project with only `find_package(ICUB)`
since icub-main has yarp libs as public dependencies but the `ICUBConfing.cmake/FindICUB.cmake` was not calling `find_package(YARP)` causing linking problems.
Example:
```cmake
cmake_minimum_required(VERSION 3.5)
project(yarpy)
find_package(ICUB REQUIRED)
file(GLOB folder_source *.cpp *.cc *.c)
file(GLOB folder_header *.h)
foreach(header_file ${folder_header})
get_filename_component(p ${header_file} PATH)
include_directories(${p})
endforeach(header_file ${folder_header})
if(folder_source)
add_executable(${PROJECT_NAME} ${folder_source} ${folder_header})
target_link_libraries(${PROJECT_NAME} ${ICUB_LIBRARIES})
else()
message(FATAL_ERROR "No source code files found. Please add something")
endif()
```
This cmake …
> Fix find_package(ICUB) after introduction CMake components in YARP.

- src/modules/camCalib/src/PinholeCalibTool.cpp
- src/modules/camCalibWithPose/src/PinholeCalibTool.cpp
- src/modules/dualCamCalib/src/PinholeCalibTool.cpp
It fixes https://github.com/robotology/yarp/issues/1979 .
The first `toCvMat(out)` has been removed since it is not necessary, and it makes the yarp and cv output image memory shared.
I am not sure but it seems that `cv::remap` does some memory changes that made crash the program while trying to write the yarp image.
This crash does not happen without using `cv::remap`.
I tested it on my laptop with `usbCamera` and now it works. 
> Fix camCalibs after the introduction of move semantic in YARP images

- conf/AddInstallRPATHSupport.cmake
- conf/iCubOptions.cmake
The AddInstallRPATHSupport.cmake file is temporarily included, until we make YCM a hard dependency.
> Fix RPATH support using AddInstallRPATHSupport from YCM

- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.h
Dragonfly device was not compiling after include cleanup.
> Dragonfly add missing include

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
This fix is concerning yarp issue [#2027](https://github.com/robotology/yarp/issues/2027) and needs yarp PR [#2035](https://github.com/robotology/yarp/pull/2035) to work properly
> EmboObjMotionControl: fix checkMotionControl(bool *flag)

- CMakeLists.txt
~~Removed 'FindPackage(ACE)' not directly used by iCub~~
Removed legacy cmake instructions
@drdanz can you double check, please? 
~~In my knowledge `ACE` is not directly used by iCub, is it right?~~  It is used
> Removed deprecated cmake instructions

- src/tools/FirmwareUpdater/mainwindow.cpp
This pr fixes the following bug:
if a can boards has been selected, the showed info belonged to a different can board.
Now, the window shows the correct info, that is the info related to the selected board.
Tested on purple icub. OK
> Fix FirmwareUpdater: 

- src/libraries/icubmod/xsensmtx/MTComm.h
Fix a compilation error while trying to compile `robotology-superbuild` with CMake option `ROBOTOLOGY_ENABLE_ICUB_HEAD` enabled.
The [clock_t](http://www.cplusplus.com/reference/ctime/clock_t/) function is not declared in `sys/time.h`, instead it's declared in time.h.
> Fix a compilation error with `ROBOTOLOGY_ENABLE_ICUB_HEAD` enabled

- src/libraries/iKin/src/iKinFwd.cpp
- src/modules/iKinGazeCtrl/src/main.cpp
As per request #570, this PR introduces IMU version **`2.6`**.
Changes are regarded with:
- `iKin` to declare the new kinematics.
Differently from what I planned, HN matrices are accumulated to adapt to the current code.
- `iKinGazeCtrl` to extend the set of allowed IMU's.
> Introduced IMU 2.6

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
In this PR I fix a wrong use of memory allocation. 
Every time the calibrate function is called, two new heap allocations are done. (see [here](https://github.com/robotology/icub-main/blob/55154efbb1d94983598f85e270c6ad145a3ba4de/src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp#L588) )
I moved such allocations in the `open` function, so they are performed one  time only. The delete is done in `close` function
> Fix memory usage in ParametricCalibratorEth

- src/tools/stereoCalib/include/stereoCalibThread.h
- src/tools/stereoCalib/src/stereoCalibThread.cpp
Hi,
I am making this pull request because recently we had to calibrate a standalone stereo camera setup. The code changes include a new flag in the stereoCalib module called "standalone" which, if set, skips the parts of the module that assume the icub to be up and running. Additionally, I allow the two cameras to have different resolution when computing the extrinsic parameters, as long as the intrinsic ones are computed beforehand.
> Added option to calibrate standalone stereo setup

- CMakeLists.txt
- app/iCubGui/scripts/iCubGui.xml.template
- app/iCubGui/scripts/iCubGui_skinContacts.xml.template
- src/tools/iCubGui/src/bvh.cpp
- src/tools/iCubGui/src/bvhnodeinertial.h
The `iCubGui` has been ported to the usage of the MAS client.
It requires yarp `3.2.101` since it uses a new option of the MAS client(robotology/yarp#2098)
Successfully tested on `iCubGenova02`.
>  iCubGui: port to the usage of MAS client 

- src/simulators/iCubSimulation/odesdl/OdeInit.cpp
- src/simulators/iCubSimulation/odesdl/OdeInit.h
- src/simulators/iCubSimulation/odesdl/iCub_Sim.cpp
- src/simulators/iCubSimulation/wrapper/SimulationRun.cpp
- src/simulators/iCubSimulation/wrapper/SimulatorModule.cpp
- src/simulators/iCubSimulation/wrapper/SimulatorModule.h
- src/simulators/iCubSimulation/wrapper/iCubSimulationIMU.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationIMU.h
Moreover it instantiates the `multipleanalogsensorsserver` that wraps the new icub sim device that expose the imu.
The port `/icub/inertial` has been maintained for backward compatibilty.
I only checked the number coming from `measures:o`, they seems ok, to be tested with `iCubGui`.
> Port the imu of iCub_SIM to the MAS interfaces`

- app/wholeBodyDynamics/scripts/wholeBodyDynamics.xml.template
- app/wholeBodyDynamics/scripts/wholeBodyDynamics_no_legs.xml.template
- src/libraries/iDyn/include/iCub/iDyn/iDyn.h
- src/libraries/iDyn/include/iCub/iDyn/iDynBody.h
- src/libraries/iDyn/src/iDyn.cpp
- src/libraries/iDyn/src/iDynBody.cpp
- src/modules/gravityCompensator/gravityThread.cpp
- src/modules/gravityCompensator/gravityThread.h
- src/modules/gravityCompensator/main.cpp
- src/modules/wholeBodyDynamics/main.cpp
- src/modules/wholeBodyDynamics/observerThread.cpp
- src/modules/wholeBodyDynamics/observerThread.h
Preface: I honestly don't know how the imu data is used in this module, i just kept the logic.
This PR add the possibility to make communicate the IMU and WholeBodyDynamics using the `multipleanalogsensorclient`.
cc @marcoaccame
> Add the MAS client usage in WholeBodyDynamics

- app/faceExpressions/conf/emotions_rfe.ini
- src/core/emotionInterface/emotionInterface.h
- src/core/emotionInterface/emotionInterfaceModule.cpp
- src/core/emotionInterface/emotionInterfaceModule.h
It has been added a new rpc request:
```bash
$ set col <color>
```
Where color is:
One of the following: black, white, red, lime, blue, yellow, cyan, magenta, silver, gray, maroon, olive, green, purple, teal, navy.
:warning: 
This new feature work only if the icub mount the new rfe board.
> Add the possibility to change the color of the face expression

- conf/FindIPOPT.cmake
See https://github.com/robotology/ycm/pull/276 .
This had already landed in devel, but it is convenient to have it in master to fix soonish https://github.com/robotology/robotology-superbuild/pull/296 .
> Backport of IPOPT_INCLUDE_DIRS fix

- src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.cpp
- src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.h
- src/libraries/icubmod/embObjFTsensor/embObjFTsensor.cpp
- src/libraries/icubmod/embObjFTsensor/eo_ftsens_privData.h
- src/libraries/icubmod/embObjInertials/embObjInertials.cpp
- src/libraries/icubmod/embObjInertials/embObjInertials.h
- src/libraries/icubmod/embObjLib/FeatureInterface.cpp
- src/libraries/icubmod/embObjLib/ethManager.cpp
- src/libraries/icubmod/embObjLib/ethManager.h
- src/libraries/icubmod/embObjLib/ethResource.cpp
- src/libraries/icubmod/embObjLib/ethResource.h
- src/libraries/icubmod/embObjLib/fakeEthResource.cpp
- src/libraries/icubmod/embObjLib/fakeEthResource.h
- src/libraries/icubmod/embObjLib/hostTransceiver.cpp
- src/libraries/icubmod/embObjLib/hostTransceiver.hpp
- src/libraries/icubmod/embObjLib/theNVmanager.cpp
- src/libraries/icubmod/embObjMais/embObjMais.cpp
- src/libraries/icubmod/embObjMais/embObjMais.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjMultiEnc/embObjMultiEnc.cpp
- src/libraries/icubmod/embObjMultiEnc/embObjMultiEnc.h
- src/libraries/icubmod/embObjSkin/embObjSkin.cpp
- src/libraries/icubmod/embObjSkin/embObjSkin.h
- src/libraries/icubmod/embObjStrain/embObjStrain.cpp
- src/libraries/icubmod/embObjStrain/embObjStrain.h
- src/tools/embObjProtoTools/boardTransceiver/boardTransceiver.cpp
- src/tools/embObjProtoTools/boardTransceiver/boardTransceiver.hpp
This PR comes along #612 and #613 with the aim to replace the following components:
- `yarp::os::Semaphore`
- `yarp::os::Mutex`
- `yarp::os::LockGuard`
- `yarp::os::Event`
with their STD counterparts:
- `std::mutex`
- `std::condition_variable`
- `std::lock_guard`
The PR applies the required changes only to **`embObj`**. 
Take into consideration the following notes:
- when a `yarp::os::Semaphore` was employed just like a mutex, then a `std:mutex` has been selected.
- when a `yarp::os::Semaphore` or a `yarp::os::Event` was employed for synchronization purposes, then a `std::condition_variable` has been selected.
- I've favored `std::lock_guard` over the most recent `std::scope_guard` because the latter is C++17 whereas the former is C++11 and for certain compilers we should be more …
> EmbObj uses std::mutex + std::condition_variable

- src/libraries/iKin/src/iKinFwd.cpp
We updated the torso limits in the correct order roll, pitch, yaw. Since the torso links are also shared by `iCubEye`, `iCubArm` and `iCubInertialSensor` we fixed also them accordingly.
This PR also fixes a missing `H(3, 3) = 1.0` within `iCubEye` V3.
> [iKin] fixed iCubTorso, iCubEye, iCubArm and iCubInertialSensor kinematics V3

- src/libraries/icubmod/embObjLib/CMakeLists.txt
- src/libraries/icubmod/embObjLib/ethReceiver.cpp
- src/libraries/icubmod/embObjLib/ethReceiver.h
- src/libraries/icubmod/embObjLib/ethSender.cpp
- src/libraries/icubmod/embObjLib/ethSender.h
- src/libraries/icubmod/embObjLib/tools/include/PeriodicEventsVerifier.h
- src/libraries/icubmod/embObjLib/tools/src/PeriodicEventsVerifier.cpp
- src/libraries/icubmod/embObjLib/tools/src/embot_tools.cpp
- src/libraries/icubmod/embObjLib/tools/src/embot_tools.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
In this PR I developed two simple classes called `Emb_PeriodicEventVerifier and Emb_RensponseTimingVerifier: the first lets you to verify the frequency of a periodic event, while the second lets you to analyze the trend of response time to a request. Both classes prints an histogram with the collected information using the yarp log system.
I used these classes to check the embedded network performance.
I was interested in verifying if the `sender` and `receiver` singletons, that manage communication between `robotinterface` and the robot embedded network, run at configured frequency.
Moreover I also analyzed the response time of a request done to the embedded board. So I used `Emb_RensponseTimingVerifier` in the function `getPidRaw`, in order to examine the needed time to get a response …
> Network performance tool

- .github/workflows/ci.yml
- src/modules/actionsRenderingEngine/include/iCub/VisuoThread.h
- src/modules/camCalib/include/iCub/CamCalibModule.h
- src/modules/camCalib/include/iCub/PinholeCalibTool.h
- src/modules/camCalib/include/iCub/SphericalCalibTool.h
- src/modules/camCalib/src/PinholeCalibTool.cpp
- src/modules/camCalib/src/main.cpp
- src/modules/camCalibWithPose/include/iCub/CamCalibModule.h
- src/modules/camCalibWithPose/include/iCub/PinholeCalibTool.h
- src/modules/camCalibWithPose/include/iCub/SphericalCalibTool.h
- src/modules/camCalibWithPose/src/PinholeCalibTool.cpp
- src/modules/camCalibWithPose/src/main.cpp
- src/modules/dualCamCalib/include/iCub/DualCamCalibModule.h
- src/modules/dualCamCalib/include/iCub/PinholeCalibTool.h
- src/modules/dualCamCalib/include/iCub/SphericalCalibTool.h
- src/modules/dualCamCalib/src/PinholeCalibTool.cpp
- src/modules/dualCamCalib/src/main.cpp
- src/modules/templatePFTracker/include/iCub/particleFilter.h
- src/tools/depth2kin/src/module.cpp
- src/tools/stereoCalib/include/stereoCalibThread.h
- src/tools/stereoCalib/src/stereoCalibThread.cpp
This PR drops the support of OpenCV 2 and add the support to OpenCV 4.
TODO:
It fixes #634
> Support OpenCV4

- CMakeLists.txt
This PR enforces the use of `YCM`.
In particular, `YCM` is employed to find `ACE`.
> Make YCM required

- src/libraries/icubmod/canBusAnalogSensor/CanBusAnalogSensor.cpp
- src/libraries/icubmod/canBusAnalogSensor/CanBusAnalogSensor.h
- src/libraries/icubmod/canBusDoubleFTSensor/CanBusDoubleFTSensor.cpp
- src/libraries/icubmod/canBusDoubleFTSensor/CanBusDoubleFTSensor.h
- src/libraries/icubmod/canBusInertialMTB/CanBusInertialMTB.cpp
- src/libraries/icubmod/canBusInertialMTB/CanBusInertialMTB.h
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.h
- src/libraries/icubmod/canBusMotionControl/ThreadTable2.cpp
- src/libraries/icubmod/canBusMotionControl/ThreadTable2.h
- src/libraries/icubmod/canBusSkin/CanBusSkin.cpp
- src/libraries/icubmod/canBusSkin/CanBusSkin.h
- src/libraries/icubmod/canBusVirtualAnalogSensor/CanBusVirtualAnalogSensor.cpp
- src/libraries/icubmod/canBusVirtualAnalogSensor/CanBusVirtualAnalogSensor.h
- src/libraries/icubmod/esdSniffer/EsdMessageSniffer.cpp
- src/libraries/icubmod/esdSniffer/EsdMessageSniffer.h
- src/libraries/icubmod/fakeCan/msgList.h
- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.cpp
- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.h
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.h
- src/libraries/icubmod/sharedCan/SharedCanBus.cpp
- src/libraries/icubmod/sharedCan/SharedCanBus.h
This PR comes along #612 #613 #614 #615 #616 #617 with the aim to replace the following components:
- `yarp::os::Semaphore`
- `yarp::os::Mutex`
- `yarp::os::LockGuard`
- `yarp::os::Event`
with their STD counterparts:
- `std::mutex`
- `std::condition_variable`
- `std::lock_guard`
The PR applies the required changes to a subset of `icubmod` components.
Take into consideration the following notes:
- when a `yarp::os::Semaphore` was employed just like a mutex, then a `std:mutex` has been selected.
- when a `yarp::os::Semaphore` or a `yarp::os::Event` was employed for synchronization purposes, then a `std::condition_variable` has been selected.
- I've favored `std::lock_guard` over the most recent `std::scope_guard` because the latter is C++17 whereas the former is C++11 and for certain …
> icubmod uses std::mutex + std::condition_variable (4)

- CMakeLists.txt
- bindings/CMakeLists.txt
This PR cleans up bindings in order to use Python-3.
If Python-3 is not found, an attempt is made to rely on Python-2 instead.
Thanks @diegoferigo for the [heads-up][1].
A test to verify the PR has been done successfully.
Be careful as https://github.com/robotology/icub-main/issues/645 has not been solved yet.
[1]: https://github.com/robotology/QA/issues/391#issuecomment-597006107
> Bindings target now Python-3

- .github/workflows/ci.yml
This PR makes use of our vcpkg prebuilt dependencies on Windows runners for doing CI.
> CI: use vcpkg prebuilt dependencies on Windows runners

- bindings/icub.i
This PR fixes #645 .
The compilation should be fine my only concern is that maybe there could be runtime issues, but I don't know how to test it. I might need help on it.
> Fix compilation of the bindings after mutexes cleanup

- conf/FindESDCANAPI.cmake
This has been already fixed  in YCM in https://github.com/robotology/ycm/pull/320 .
The fix is backported to the master branch of icub-main to simplify the integration of esdcan-binary vcpkg port in the existing CI infrastructure, see https://github.com/robotology/robotology-superbuild/pull/397 .
> Fix use of FindESDCANAPI.cmake with esdcan-binary vcpkg port

- src/tools/iCubGui/src/bvhnodeeye.h
I am not an expert of glut, but apparently there are functions that start with `glu***` and take in input a pointer to `GLUquadricObj`, and functions that start with `glut` and do not take in input a pointer to `GLUquadricObj`. BVHNodeEYE  was the only class that used a `glut***` function, and during the call when used with freeglut installed via vcpkg it was crashing  with error: 
~~~
Exception thrown: read access violation.
fgStructure.**CurrentWindow** was nullptr. occurred
~~~
and the backtrace was: 
~~~
freeglutd.dll!fghDrawGeometrySolid(float * vertices, float * normals, float * textcs, int numVertices, wchar_t * vertIdxs, int numParts, int numVertIdxsPerPart) Line 181	C
freeglutd.dll!fghSphere(float radius, int slices, int stacks, unsigned char useWireMode) Line 1721	C …
> iCubGui: In BVHNodeEYE switch from glutSolidSphere to gluSphere

- .github/workflows/ci.yml
- bindings/CMakeLists.txt
- src/tools/canLoader/canLoaderLib/CMakeLists.txt
This cleanup make possible to compile the bindings from a clean build.
In this sense I enabled it in the CI for see if now they works.
> Fix bindings compilation from a clean directory

- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
While it make sense to print an error if non implemented method are called, for the case of getCurrentRangeRaw-related methods, these methods are called whenever a yarpmotorgui  client connects to CanBusMotionControl, even if the current control mode is not used, so just printing a warning is probably enough.
cc @xEnVrE @randaz81
> CanBusMotionControl: do not print an error if getCurrentRangeRaw is used

- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
If motorPwmLimit is not found, the default limit of 1333 is used instead, and a warning is printed. 
For this reason, it does not make sense to print an error if motorPwmLimit is  not found.
> CanBusMotionControl: do not raise error if motorPwmLimit is not found

- src/libraries/iKin/include/iCub/iKin/iKinFwd.h
- src/libraries/iKin/src/iKinFwd.cpp
This PR adds up the new kinematics chain `iCubInertialSensorWaist` that accounts for the IMU mounted in the waist of the iCub 2.7.
Further, the kinematics of all limbs take version 2.7 into account as well.
I also took the opportunity to streamline the handling of HW versions for some of the available limbs. Thus, it might be difficult to review the PR since the line-by-line comparison is compromised 😞 
The new chain contains **no joints but only a fixed H0**, therefore the following snippet (provided in this attached [archive][1]):
```c++
iCubInertialSensorWaist sensor;
cout << "H =" << endl << sensor.getH().toString(3, 3) << endl;
cout << "DOF = " << sensor.getDOF() << endl;
cout << "Ang = " << sensor.getAng().toString(3, 3) << endl;
```
will yield (when compiled in `Release`):
```
H = …
```
> Added iCubInertialSensorWaist for iCub v2.7

- app/faceExpressions/conf/emotions_rfe.ini
- src/core/emotionInterface/emotionInterfaceModule.cpp
- src/core/emotionInterface/emotionInterfaceModule.h
This PR add the commands for controlling the eylids in the rfe iCub.
In particular in `emotion_rfe.ini` the eyelids column has been changed, the value is no more HEX but a representation of `% open`
E.g.
`00p` -> 0% open
`01p` -> 10% open
`05p` -> 50% open
`10p` -> 100% open
It has to be tested on both old and new robots.
> emotioninterface: add the command for controlling the eyelids for the rfe configuration

- conf/ICUBConfig.cmake.in
Since #652 `find_package(ICUB)` shadows previous `find_package(YARP)` calls, this PR fix this problem.
> Fix iCub config

- src/modules/wholeBodyDynamics/main.cpp
Upon analyses @julijenv reported in https://github.com/robotology/icub-tech-support/issues/976, this PR does the following:
- Increase the reading timeout of IMU data from 0.04 s to 0.1 s as it was in the past. @Nicogene any clue why this has been made tighter?
- Make the filtering thread run at 100 Hz instead of 1 kHz, which was unnecessarily too high given the sampling frequency of the received data plus streaming the results at 1 kHz on YARP is hazardous. 
@Nicogene @traversaro please review/comment.
After merging, we need to update `devel` and then tags `1.16.1` and `1.17.0`.
cc @maggia80 @marcoaccame @davidetome @violadelbono
> [WBD] fixed handling of MAS periodicity

- src/tools/FirmwareUpdater/firmwareupdatercore.cpp
- src/tools/FirmwareUpdater/firmwareupdatercore.h
- src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp
This PR allows configuring the IP's of the EMS boards through the `FirmwareUpdater` as per the request in https://github.com/robotology/QA/issues/423.
> FirmwareUpdater - configurable IPs

- src/tools/FirmwareUpdater/main.cpp
* adding CLI option to load .dat calibration file for strain2
* - added CLI option and method scheleton
* loading calibration file to STRAIN2 eeprom works using SOCKETCAN device - wip
* loading calibration file to STRAIN2 eeprom works using ETH device
* added check on CAN line number - minor fixes
* added check if CAN boardtype is STRAIN2 - minor fixes
> added CLI option to FirmwareUpdater- Fix/issue 499 

- src/tools/FirmwareUpdater/main.cpp
`canLine` and  `canId` were cabled in the code
cc @triccyx
> FirmwareUpdater fixed bug in saveDatFileStrain2 

- .ci/packages_vars.sh
It adds the boost dependencies for the [robot testing profile of the superbuild](https://github.com/robotology/robotology-superbuild#profile-cmake-options).
cc @violadelbono @julijenv
> Update packages_vars.sh for 2020.11 release

- app/faceExpressions/doc.dox
- app/faceExpressions/scripts/exampleTransition.sh
- src/core/emotionInterface/emotionInterfaceModule.cpp
This is a followup of #697 , sorry I didn't noticed these errors in time
Please review code
cc @violadelbono @julijenv
> faceExpressions: more fixes to the doc

- src/libraries/iKin/src/iKinFwd.cpp
- src/modules/gravityCompensator/gravityThread.cpp
It needs more investigations, but for now this make works gravityCompensator
TO BE TESTED on the robot (cc @violadelbono @julijenv )
> gravityCompensator: fix crash due to a move operator after a resize

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
Under Windows using `reserve` without any `resize` throws a "out of range" exception. 
This is due to the fact that after that `reserve` the `capacity` is `nj`, the size is `0`.
I am surprised that this code is allowed under linux, but maybe I am missing something.
BTW this code is tested on windows and it works
> embobjMotionControl: fix windows execution

- bindings/icub.i
As per the title, this PR add SWIG support for `std::deque<yarp::dev::IControlLimits*>` that is used, among others, in `iCub::iKin` derived classes implementing the method `alignJointsBounds`.
Fixes #710
> [SWIG] Add support for std::deque of yarp::dev::IControlLimits*

- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjLib/serviceParser.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
This PR allows `embObjMotionControl` to move the fingers of the new hand in open close mode.
As such, we can now parse xml files which have the field `SERVICE.type`  equal `eo_motcon_mode_mc4plusfaps`.
This service type needs a mc4plus board of which uses the standard pwm actuators on ports `CONN:P2`, `CONN:P3`, `CONN:P4` and `CONN:P5`. 
The novelty in here is that the encoders at joint are described as `POS:hand_thumb`, `POS:hand_index`, `POS:hand_medium` and `POS:hand_pinky` and are associated to absolute magnetic encoders placed on the `fap` boards which are managed by CAN board `pmc` of which we specify CAN address in the field `POS.location`.
So we needed the parsing of the xml to be able to get the new parameters and to send then to a `mc4plus` board and then down to the `pmc` …
> Movement of the fingers of the new hand in open/close mode

- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
This pull request introduces a warning message when the configuration of position control PID is not consistent across the different joints, resulting in wrong values for the PIDs (mismatching between `machine_units` and `metric_units`).
This PR addresses [this issue](https://github.com/robotology/icub-main/issues/712).
@randaz81 : This implementation covers **only position control**, since the configuration for other types of control is slightly different. Should this be implemented for all different types of control?
> Warning message for position control PID when config not consistent

- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
This PR fixes issue #718 .
Since we have an array of PidInfo / TrqPidInfo, we can't rely on class inheritance to query the parameters of each PID ([an array of Derived is not a kind-of array of Base][1]). As such, we need to check if the PID type is torque and handle it differently.
[1]: https://www.cs.technion.ac.il/users/yechiel/c++-faq/array-derived-vs-base.html
> fixed the checkJointTypes function for the case of TORQUE control

- CMakeLists.txt
For some experiments I am doing with generation of conda binaries, it would be convenient to tag 1.19.1 that includes https://github.com/robotology/icub-main/pull/724, what do you think @Nicogene ?
> Bump version to 1.19.1

- conf/iCubFindDependencies.cmake
This pull-request is a child of this other pull-request: [https://github.com/robotology/icub-firmware/pull/170](https://github.com/robotology/icub-firmware/pull/170).
It forces icub-main to use the most recent changes in icub-firmware (according to the parent PR).
CC @pattacini
> icub-firmware version bump

- src/libraries/icubmod/bcbBattery/README.md
- src/libraries/icubmod/bcbBattery/bcbBattery.cpp
- src/libraries/icubmod/bcbBattery/bcbBattery.h
This PR attempts at improving the ``bcbBattery`` module, fixing the following issues:
- ``thread_period`` was not found in the conf file and most probably assumed to be zero.
- A mutex was missing in the close method causing data races on the use of the serial device.
- The voltage and current values were not divided by 1000 (the board sends the values in mV and mA)
- It was not properly checked if the char were read correctly or not. Most of the times, the read values were from uninitialized memory.
- The sync mechanism seemed to have issues
- The methods returning the battery status and temperature were always returning false, avoiding the BatteryWrapper to stream the values.
- The print of the received buffer was not readable.
In addition, I added the following:
-  A parameter to avoid …
> Improvements on the BCB battery module

- src/modules/gravityCompensator/gravityThread.cpp
- src/modules/wholeBodyDynamics/observerThread.cpp
This bug was hidden by the fact in the past the `yarp::sig::Vector` by default preallocated 16 elements. Calling e.g. `getEncoders` with a smaller vector made this function call write in forbidden memory areas.
With these fixes they do not crash anymore, and they close gracefully
(I know that I should retrieve the number of joints and not hardcode them, but this executable will be replaced soon.)
> Fix wholeBodyDynamics and gravityCompensator memory leaks

- .github/workflows/ci.yml
`FindFFMPEG.cmake` returns that the component is found even if not all libraries are installed (e.g. `libavdevice-dev`).
This is causing problems in CI: see for example https://github.com/robotology/icub-main/runs/2198575453?check_suite_focus=true.
cc @drdanz @Nicogene
> Disable finding FFMPEG in CI

- src/libraries/ctrlLib/CMakeLists.txt
- src/libraries/ctrlLib/include/iCub/ctrl/math.h
- src/libraries/ctrlLib/src/math.cpp
This PR addresses #717.
Instead of resorting to the CMake infrastructure to export the constants, I've verified that declaring those identifiers as `constexpr` made the trick, both in shared and static building.
@traversaro I believe this way is simpler to be maintained.
What's your opinion?
> Make ctrlLib constants constexpr

- src/modules/actionsRenderingEngine/src/MotorThread.cpp
This PR fixes #740.
I took the chance to analyze the problem by using the following snippet:
```c++
#include <cstdlib>
#include <typeinfo>
#include <string>
#include <iostream>
#include <iCub/action/actionPrimitives.h>
void test(const int i, const bool cond) {
std::cout << "test " << i << ": "
<< (cond ? "passed ✅" : "failed ❌")
<< std::endl;
}
int main() {
iCub::action::ActionPrimitives* action = new iCub::action::ActionPrimitivesLayer2();
test(1, typeid(action).name() == typeid(iCub::action::ActionPrimitivesLayer2).name());
test(2, typeid(*action).name() == typeid(iCub::action::ActionPrimitivesLayer2).name());
test(3, dynamic_cast<iCub::action::ActionPrimitivesLayer2*>(action));
test(4, typeid(action) == typeid(iCub::action::ActionPrimitivesLayer2));
test(5, typeid(*action) == …
```
> Fix `ARE` check on action type

- src/libraries/icubmod/imuFilter/ImuFilter.cpp
- src/libraries/icubmod/imuFilter/ImuFilter.h
This PR aims to fix #728.
To this end, the option `period` is handled in `ms` instead of `s`, plus the default value is brought to 20 ms instead of 10 ms in order to prevent the generation of continuous warning: we take a sampling margin wrt the rate of the incoming data, which is 10 ms.
> Fix imuFilter sampling of incoming data

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
This PR allows `yarprobotinterface` to manage the 7 joints of the mk3 hand for what is about the FW on the `mc4plus` and `pmc` boards.
This PR is part of a set of PRs which should be processed all together. More details are in [here](https://github.com/robotology/icub-firmware/pull/179).  
For the sake of this repo, the changes have been limited to:
- the way `embObjMotionControl` parses the xml files of mode called `eomn_serv_MC_mc4pluspmc` and forms the data structure required for its configuration.
- requirement of a new version of `icub-firmware-shared` which is now still in a private fork (see the [PR](https://github.com/robotology/icub-firmware-shared/pull/47)). For this reason, ... I suspect that the test of continuous integration will fail (cc @pattacini).
> Support of 7 joints in the mk3 hand

- app/skinGui/conf/skinGui/right_upperarm_V3.ini
This patch fixes the skinGui visualization for right upperarm on v3. This is following the support ticket https://github.com/robotology/icub-tech-support/issues/1134 for checking if the right upperarm skin triangle patches numbered `6` and `8` are not working. Thanks to @simeonedussoni who pointed that it is the configuration file problem.
https://user-images.githubusercontent.com/6505998/118624359-6114e180-b7c9-11eb-93d2-1e7ea8482d93.mp4
https://user-images.githubusercontent.com/6505998/118624367-62460e80-b7c9-11eb-87af-79fb5204a158.mp4
CC @S-Dafarra @DanielePucci
> Update right upperarm v3 skingui config file

- src/libraries/icubmod/bcbBattery/bcbBattery.cpp
- src/libraries/icubmod/bcbBattery/bcbBattery.h
Some changes to: https://github.com/robotology/icub-main/pull/727
Main changes and explanation:
I did some experiments and I noticed that the previous implementation was too much dependent on the thread period: a wrong value could cause severe misbehavior.
- If the thread period was too small, not enough characters were received in the internal buffer. So all the receiver_character() calls become blocking for the number of milliseconds specified in the configuration file (default = 5ms)
- If the thread period was too large, many packets (i.e. blocks of 10 bytes) were placed in the buffer, but the parsing function was just getting the first (old) one. I added a flush() to avoid that the buffer increases in size indefinitely, however, I still was not happy with the solution.
So: this is the …
> BcbBattery

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjLib/serviceParser.h
This PR adds runtime configuration of additional diagnostics useful for debugging services on the robot. 
Runtime configuration means that yarprobotinterface collects some parameters from xml files and sends them to the ETH boards so that this one can use them to activate / tune some actions.
So far, only the AMO diagnostics in MC service is supported. 
See https://github.com/robotology/icub-firmware/pull/187
The CI test needs https://github.com/robotology/icub-firmware-shared/pull/48 to be merged first otherwise it will fail.
> AMO diagnostics

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/hostTransceiver.cpp
- src/libraries/icubmod/embObjLib/protocolCallbacks/EoProtocolMC_fun_userdef.c
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
This PR belongs to a set of PRs which enable to stream AMO data towards YARP ports.
See robotology/icub-firmware#188 for details.
To enable the features of this PR we also need similar PRs. They are:
- in [`icub-firmware-shared`](https://github.com/robotology/icub-firmware-shared/pull/49) which contains the data structures,
-  in  [`icub-firmware`](https://github.com/robotology/icub-firmware/pull/188) we have the code for the ETH boards
- in [`icub-main`](https://github.com/robotology/icub-main/pull/753) which contains code to publish on the YARP port.
- in [`icub-firmware-build`](https://github.com/robotology/icub-firmware-build/pull/30) to give the new binaries for the `ems`, `mc4plus`, `mc2plus`.
> AMO data to YARP ports

- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
`ImplementPositionControl2`, `ImplementVelocityControl2` were deprecated in YARP 3.0 (see https://github.com/robotology/yarp/blob/v3.0.0/doc/release/v3_0_0.md#yarp_dev). At some point there was a cleanup (in https://github.com/robotology/icub-main/pull/538 and probably other PRs) but some uses were still missing. This PR removes the remaining uses, and ensure that icub-main compiles fine with the upcoming YARP 3.5 .
Fix part of https://github.com/robotology/robotology-superbuild/issues/794 .
> Remove references to deprecated YARP interfaces

- conf/iCubFindDependencies.cmake
As the logic was now, it was impossible for a user to disable the use of icub_firmware_shared  if the wrong versions was installed.
> Only raise a fatal error on icub_firmware_shared version if icub_firmware_shared is used

- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.h
This PR addresses what in issue https://github.com/robotology/icub-main/issues/754 and fixes:
- compilation warnings
- potential bugs
- `CanBusMotionControl::setControlModeRaw()` and similar methods did not return false when they receive an invalid control mode.
- in some c-string manipulation there was the danger to write out of memory in case the string is very long.
There are two changes:
- fix of the behaviour / use of function `CanBusMotionControl::from_modevocab_to_modeint()` used inside `::setControlModeRaw()` to transform a `yarp::conf::vocab32_t` into a `icubCanProto_controlmode_t`.
- fix of the creation of a string to be printed with yDebug() inside method `void CanBusMotionControl::run()` 
In the first case, the return value of `from_modevocab_to_modeint()` was compared vs …
> CanBusMotionControl: corrected compilation warnings + potential bugs

- src/simulators/iCubSimulation/odesdl/MS3D.cpp
- src/simulators/iCubSimulation/odesdl/MS3D.h
- src/tools/skinManagerGui/CMakeLists.txt
> Fix name clash with `std::byte`

- src/libraries/icubmod/embObjLib/CMakeLists.txt
- src/libraries/icubmod/embObjLib/mcEventDownsampler.cpp
- src/libraries/icubmod/embObjLib/mcEventDownsampler.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
This PR aims to fix the issue: https://github.com/robotology/icub-main/issues/768
To downsample the error messages rate, the logic of a simple Finite State Machine is implemented inside a `yarp::os::Timer`. The timer runs at 100Hz. If they exceed a threshold of 5 events, the FSM prints the number of error events occurred each second. 
The proposed solution was tested on a desk setup with one joint, addressing the three  types of error events mentioned in the issue.
The videos below show the results on the setup.
On the top left there's the `Yarpmotorgui`, where I change the control mode. On the top right there's the program `tutorial_arm` that sends the requests, and triggers the errors in the `yarprobotinterface` if the control mode is not the expected one. On the bottom there is the …
> Add message downsampler to avoid logger flooding when changing control mode

- src/libraries/icubmod/embObjLib/mcEventDownsampler.cpp
- src/libraries/icubmod/embObjLib/mcEventDownsampler.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
This PR follows up on #770 and lets the downsampler print out info about the board as well.
I've also streamlined the code here and there where/when possible.
> Add board info to the downsampler

- src/libraries/icubmod/embObjLib/mcEventDownsampler.cpp
- src/libraries/icubmod/embObjLib/mcEventDownsampler.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
This PR follows up on #771 and allows for configuring the `threshold` and the `subcomponent` name.
The latter might be required as the downsampler is in the library and could be utilized in the future also for different goals other than the MC.
> Configuration of `threshold` and `subcomponent` of the message downsampler

- src/tools/FirmwareUpdater/main.cpp
This PR introduces the `FirmwareUpdater CLI` capability to change : 
- CAN board ID via `SOCKETCAN` device
- CAN board ID via `ETH` device  
- IP address of an ETH board
In this example, we change the `CAN ID` on an `mtb` board connected via `SOCKETCAN` from 1 to 2.
The syntax of the command is the following : 
```bash
FirmwareUpdater -g -e SOCKETCAN -i 0 -c 0 -n 1 -k 2
```
where : 
- `-g -e SOCKETCAN -i 0 -c 0` is need to use a `SOCKETCAN` device (i.e. `ESD CAN/USB`) with `ID=0` and `canline=0`
- `-n 1 -k 2` changes old id 1 (-n 1) to 2 (-k 2)
https://user-images.githubusercontent.com/6638215/143570541-aab0d7ac-a9c9-45e3-b3c9-195622be5d4e.mp4
In this example, we change the `CAN ID` on an `mtb` board connected via `ETH ` through an `ems4` board w/ `IP address = 10.0.1.1` from 1 to 2.
The …
> Added CLI options for change CAN ID and IP address

- conf/iCubFindDependencies.cmake
- src/tools/canLoader/canLoaderLib/downloader.cpp
This PR allows the program `FirmwareUpdater` to recognize the boards `pmc` and `amcbldc` for its operativity.
For this purpose, we need to define some enum values in `icub-firmware-shared` (see the relevant [PR](https://github.com/robotology/icub-firmware-shared/pull/51)) and to avoid compilation failure we also need to update the required version of icub-firmware-shared to be 1.22.1.
A small but important change was to increase the timeout with which the `canloader` library waits for a reply from the `amcbldc` and `pmc` after it has sent them a `BOOTLOADER:board` message. The reason is that these two new boards require longer time to perform their FLASH erase.
For further details see also the following joint PR in [icub-firmware](https://github.com/robotology/icub-firmware/pull/222), …
> Added support for amcbldc and pmc boards in FirmwareUpdater

- src/tools/FirmwareUpdater/main.cpp
@marcoaccame 
I have added two new params:
- j4 set the gains to FT45 default
- j5 set the gains to FT58 default
-j is still present and is mapped on -j4
Could you verify if this approach is good for you? Otherwise, we can discuss an alternative.
@davidetome @pattacini
> added default values for FT58 and FT45

- .ci/create_icub-main_deb.sh
- .ci/packages_vars.sh
Since now yarp requires cmake 3.16.0 or higher, we had to install it on buster using the backports
> Fix packets generation for debian buster

- conf/iCubFindDependencies.cmake
This PR forces the use of the latest `icub-firmware-shared` version, now icub_firmware_shared_VERSION 1.24.1 as from [PR](https://github.com/robotology/icub-firmware-shared/pull/58).
> Forced use of icub_firmware_shared_VERSION 1.24.1

- src/tools/iCubGui/src/CMakeLists.txt
The `OpenGL_LIBRARIES` variable is not provided by the official CMake OpenGL module, see https://cmake.org/cmake/help/latest/module/FindOpenGL.html . That variable was provided by the YCM's `FindOpenGL` module, that was removed in https://github.com/robotology/ycm/pull/401 . 
To avoid problems in linking OpenGL, this PR switches to use the CMake target `OpenGL::GL` as suggested in CMake docs.
> iCubGui: Remove use of legacy OpenGL_LIBRARIES CMake variable

- src/tools/iCubGui/src/CMakeLists.txt
https://github.com/robotology/icub-main/pull/787 was incomplete, as `iCubGui` is also using GLU.
> Add link on OpenGL::GLU for iCubGui

- .github/workflows/ci.yml
- CMakeLists.txt
This PR fixes #784.
@sgiraz narrowed down the reason why part of the libraries was ok and part not. See below.
I've also reinstated the test stage of the CI on Windows.
---
After a quick comparison between commit [87cd0a1][1] and commit [b6e0f7b][2] I found the difference that caused the "fix".
In particular in [`src/libraries/icubmod/embObjLib/CMakeLists.txt`][3] we have the following difference:
```diff
- add_library(${PROJECT_NAME} SHARED ${embobj_source} ${embobj_header})
+ add_library(${PROJECT_NAME} ${embobj_source} ${embobj_header})
```
As we can see, the SHARED keyword has been removed in [b6e0f7b][2].
[1]: https://github.com/robotology/icub-main/commit/87cd0a1df4c6b52c5876a5c7e7969cd60299d408
[2]: https://github.com/robotology/icub-main/commit/b6e0f7b471437efa82172ee757db116fb210b …
> Fix placing of shared libraries in Windows

- src/tools/joystickCtrl/main.cpp
This PR makes it less confusing to add new actions for buttons on the joystick. The problem was that the do_while used to break if it couldn't find a specific button in order.
For example if you specified:
button0 ...
button1 ...
button3 ...
It would only add to the list the buttons 0 and 1 and then break, never including button3. The new logic uses a for loop (we have specified number of buttons) and loops through all of the indexes and tries to add them. This allows for the behavior above to work correctly without changing the existing behavior.
> Allow reading joystick buttons executables without including all

- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.h
Fix https://github.com/robotology/icub-main/issues/794 . As `IFrameGrabberControls2` was a typedef for `IFrameGrabberControls` since YARP 3.0 it is safe to do this change in master branch.
> Do not use deprecated IFrameGrabberControls2 interface

- src/unittest/CMakeLists.txt
On a local Windows PC this fix works. The UTs now are correctly compiled
> Fix unittest for Windows

- src/libraries/icubmod/embObjLib/CMakeLists.txt
- src/libraries/icubmod/embObjLib/ethReceiver.cpp
- src/libraries/icubmod/embObjLib/ethSender.cpp
- src/libraries/icubmod/embObjLib/tools/include/PeriodicEventsVerifier.h
- src/libraries/icubmod/embObjLib/tools/src/PeriodicEventsVerifier.cpp
Alongside with @vvasco, we fixed the tools inside the embObjLib for test network performance.
In details:
- we updated the cmake file: now the option `NETWORK_PERFORMANCE_BENCHMARK`, that enables the tool, works properly.
- we fixed `Emb_PeriodicEventVerifier`: now it uses the correct measure units.
- we fixed a bug about the casting from int to double.
- we updated the print histogram function.
We already used these changes to test the network performance on a robot. All is fine.
> Fix net performance tool in embObjLib

- src/libraries/icubmod/embObjMultipleFTsensors/README.md
Fix UOM for times in documentation
> Minor doc fix

- app/simConfig/conf/Sim_head.ini
- app/simConfig/conf/Sim_left_arm.ini
- app/simConfig/conf/Sim_left_leg.ini
- app/simConfig/conf/Sim_right_arm.ini
- app/simConfig/conf/Sim_right_leg.ini
- app/simConfig/conf/Sim_torso.ini
- src/libraries/icubmod/canBusMotionControl/CMakeLists.txt
- src/libraries/icubmod/embObjMotionControl/CMakeLists.txt
- src/simulators/iCubSimulation/wrapper/SimulatorModule.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
This PR aims to remove some leftovers after the `controlboardwrapper2` has been declared deprecated in https://github.com/robotology/yarp/pull/2834. The new intended device is thus`controlBoard_nws_yarp`.
In particular, `controlBoard_nws_yarp` does not handle the remapping of the joints as it leverages a specific device for that; instead, the old `controlboardwrapper2` was capable of doing remapping as well. As a result, `controlBoard_nws_yarp` does not consider the option `AxisMap`.
Main components affected:
- `iCub_SIM` (is deprecated in favor of Gazebo but it still remains a nice-to-have)
- `canBusMotionControl`
- `embObjMotionControl`
- `AxisMap` completely removed w/o problems as no remapping was performed at all.
- Still need to verify the interaction between …
> Replace `controlboardwrapper2` w/ `controlBoard_nws_yarp`

- src/libraries/icubmod/embObjLib/ftInfo.h
- src/libraries/icubmod/embObjLib/serviceParserMultipleFt.cpp
- src/libraries/icubmod/embObjMultipleFTsensors/embObjMultipleFTsensors.cpp
- src/unittest/testServiceParserForMultipleFT.cpp
Bug fix relating to temperature acquisition period for multiple FT sensor device
> Fixed handling of temperature in MultipleFT service

- .github/workflows/ci.yml
- src/libraries/icubmod/embObjBattery/CMakeLists.txt
- src/libraries/icubmod/embObjMultipleFTsensors/CMakeLists.txt
This PR enables the CI for `embObjBattery`, which was off apparently for #793.
cc @triccyx
> Enable CI for `embObjBattery` + fix deps on `YARP`

- src/libraries/icubmod/embObjLib/ftInfo.cpp
- src/libraries/icubmod/embObjLib/ftInfo.h
- src/libraries/icubmod/embObjLib/serviceParserMultipleFt.cpp
- src/libraries/icubmod/embObjMultipleFTsensors/embObjMultipleFTsensors.cpp
- src/libraries/icubmod/embObjMultipleFTsensors/embObjMultipleFTsensors.h
- src/unittest/testServiceParserMultipleFT.cpp
Fix frame name for multipleFTSensors
This is the first step done for MultipleFtSensor to understand if this fix is correct @randaz81
> Fix frame name for multipleFT sensors

- src/libraries/icubmod/embObjMultipleFTsensors/embObjMultipleFTsensors.cpp
This PR fixes a bug in `embObjMultipleFTsensors` where temperature was wrongly displayed.
For instance, a value of 31 degrees was published as 310.
Now the temperature is correctly published in Celsius degrees.
> Fixed `embObjMultipleFTsensors`: now temperature is published in Celsius degrees

- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
What's new in this PR:
- Update `eomcParser` to set a default value (zero) for the friction parameters when they are not included in the config files.
**Notes:**
- When friction parameters are not included in configuration files, the `yarprobotinterface` log shows a warning instead of an error and sets the friction parameters to zero. 
- Tested on AEA2 setup
cc @pattacini @isorrentino @marcoaccame
> Update `eomcParser` to set a default value (zero) for the friction parameters when they are not included in the config files.

- src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp
What's new:
- Add a new macro `ETH_MAINTAINER_DISCOVER_UNICASTMODE` to enable the `FirmwareUpdater` to discover:
- The default address for boards like `AMC` and `AMCBLDC` --> `10.0.1.99`
- Any address between `10.0.1.1` and `10.0.1.32` assigned by the user
**Notes:**
None
> Update EthMantainer to support discovering in unicast mode

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
What's new:
- the `parse2FocGroup` has been renamed to `parseFocGroup` and it has been extended to include the `groupName` param valid for either `2FOC` and `AMCBLDC`
- rename `twofocinfo` to `foc_based_info` to be compliant with the meaning of `foc-based`
- removed unused `iMange2focBoards` function
- save the board type in `ServiceParser::parseService`
- minor cleanup of some old comments
**Notes**
- tested on `lego-setup`
cc @pattacini @valegagge @ale-git @mfussi66
> Update `serviceParser` + `eomcParser` + `embObjMotionControl` to support `amcbldc` boards in xml files

- .github/workflows/ci.yml
As per the title.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path.
> Extend path using `GITHUB_PATH` in the CI

- src/libraries/iKin/src/iKinFwd.cpp
- src/modules/iKinGazeCtrl/src/main.cpp
This PR appends an end effector matrix HN to the DH table of `iCubEye` to account for the displacement between the eyes pan joints and the new camera sensors. The displacement is only along the Z axis by 5.4mm  (which is normal to the ccd), therefore we can add a matrix like:
```
1 0 0  0
0 1 0  0
0 0 1 -5.4e-3
0 0 0  1
```
cc @pattacini @Nicogene @salvi-mattia
> Add eye kinematics modification for new cameras

- src/libraries/icubmod/embObjLib/serviceParser.cpp
This PR fixes the boolean expression that is used when checking the type of strain2 board.
If it's `OR` and the board is strain2, the `yarprobotinterface` fails the launch. Otherwise, with `AND` it fails only when the board is different from strain2 and strain2c
> Fix boolean expression when checking type of strain2 board

- CMakeLists.txt
- src/libraries/iKin/include/iCub/iKin/iKinFwd.h
- src/libraries/iKin/src/iKinFwd.cpp
Apparently, `major` and `minor` are system-defined macros on some platforms.
See https://github.com/robotology/robotology-superbuild/issues/1313.
> [iKin] fixed clash with system macros

- .github/workflows/ci.yml
This PR also solves the rate limited access to retrieve the latest release of the vcpkg dependencies zip.
> [CI] use `iwr` and `gh` for windows

- CMakeLists.txt
The `ICUB_GENERIC_VERSION` and `ICUB_GENERIC_SOVERSION` variables were added in https://github.com/robotology/icub-main/commit/8f3233974a87591710a5e549a04fec59d24c9816, but at some point the code that defined them was removed, and this deadcode was left behind. In this PR I just propose to remove them,  as anyhow we are not mantaning precise soversion in icub-main.
> Cleanup use of undefined ICUB_GENERIC_(*)VERSION CMake variables

- .github/workflows/ci.yml
- src/tools/canLoader/canLoader-console/CMakeLists.txt
- src/tools/strainCalib/strainCalibLib/CMakeLists.txt
Ädd missing link between `strainCalibLib` and `canLoaderLib` to fix compilation with `BUILD_SHARED_LIBS` set to `ON`. To avoid future regressions, I also added tests with BUILD_SHARED_LIBS=ON . If we want to avoid to double the number of tests, we can also switch to use `BUILD_SHARED_LIBS` by default.
> Fix BUILD_SHARED_LIBS set to ON and add test

- src/libraries/icubmod/embObjIMU/eo_imu_privData.cpp
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjLib/serviceParser.h
`sensorName` is **optional**, if defined it is used as return of `get<type>SensorName` and for now also `get<type>FrameName`, (we should in the future also add `frameName`  as done #822 ) otherwise `id` is used.
It fixes #852 
cc @traversaro @marcoaccame @pattacini
> embObjIMU: add sensorName param

- conf/iCubFindDependencies.cmake
- src/libraries/learningMachine/standalone/CMakeLists.txt
- src/modules/learningMachine/standalone/CMakeLists.txt
- src/tools/FirmwareUpdater/firmwareupdatercore.cpp
- src/tools/FirmwareUpdater/firmwareupdatercore.h
- src/tools/FirmwareUpdater/main.cpp
- src/tools/FirmwareUpdater/mainwindow.cpp
- src/tools/FirmwareUpdater/mainwindow.h
- src/tools/FirmwareUpdater/mainwindow.ui
- src/tools/canLoader/canLoaderLib/downloader.h
- src/tools/embObjProtoTools/boardTransceiver/CMakeLists.txt
- src/tools/embObjProtoTools/embObjProto_debugParser/CMakeLists.txt
- src/tools/embObjProtoTools/nvListPrinter/CMakeLists.txt
- src/tools/emsBackDoorManager/CMakeLists.txt
- src/tools/ethLoader/ethLoaderLib/EthBoard.h
- src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp
- src/tools/ethLoader/ethLoaderLib/EthMaintainer.h
- src/tools/ethLoader/ethLoaderLib/EthUpdater.cpp
- src/unittest/CMakeLists.txt
**What's new:**
- EthMaintainer now uses the new `eOuprot_cmd_DISCOVER_REPLY2_t` to parse the reply coming from the AMC multi-core family boards. 
- A new `uprot_OPC_DISCOVER2` help the `processDiscoveryReplies2` to discriminate the parsing strategy, maintaining the back-compatibility with the existing ones. 
- `prepareMoreInfoText` now parses the info contained in the `extraprocesses` when they exist.
- Align all the `cmake_minimum_required` to VERSION 3.12
- A new `Erase Application` button is visible when running the `Firmwareupdate` with the administrator privileges (`-a`)
- Add a new warning (⚠️) icon to the dialog window when we try to discover the CAN boards through ETH boards that are running the default application
- Add some useful comments in `EthUpdater.cpp`
- Remove previous …
> `Firmwareupdater` – Add support for other processes on multi-core boards

- conf/iCubFindDependencies.cmake
**What's new:**
- In order to see the new diagnostics messages generated by the AksIM2 encoder we have to use `icub-firmware-shared` v1.31.0 which contains the new (human-readable) diagnostics messages to visualize on the `yarprobotinterface`
**Notes:**
> Update required `icub_firmware_shared_VERSION` to 1.31.0 for AksIM2 encoder

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
This PR allows the correct parsing of the POS section of the xml files used for MC in the new hand of `ergoCub` with also the `mtb4` and `mtb4c` boards.
It is associated to:
- https://github.com/robotology/icub-firmware/pull/347
- https://github.com/robotology/icub-firmware-shared/pull/79
- https://github.com/robotology/icub-firmware-build/pull/69
> POS can use also `mtb4` and `mtb4c` boards

- conf/iCubFindDependencies.cmake
This PR just ... force to use `icub-firmware-shared` v 1.32.1 because of new names for hand mk5.
It requires this PR to merged first:
- https://github.com/robotology/icub-firmware-shared/pull/78
> HandMK5: force the use of the latest icub-firmware-shared

- app/default/scripts/cameras_calib.xml.template
- app/default/scripts/cameras_calib_bayer_320_240.xml.template
- app/default/scripts/cameras_calib_bayer_640_480.xml.template
As discussed in [#469](https://github.com/robotology/robots-configuration/pull/469), this PR aims to delete the `grabberDual` references already present in icub-main.
> Delete grabberDual references

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
Here we added the code for calibration 14 parameters parsing.
Even if the calibration 14 parameters hosts both motor encoder info and joint encoder (`FAP`)info,  currently only the data regarding the motor encoder are used: `pwmlimit` and `final_pos.` 
This PR is related to this fw [PR](https://github.com/robotology/icub-firmware/pull/363) and to this icub-firmware-shared [PR](https://github.com/robotology/icub-firmware-shared/pull/81)
> Added calibration 14 in embObjMotionControl manages calib 14

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.h
During the investigation of [this ticket](https://github.com/robotology/icub-tech-support/issues/1544), @MSECode and I noticed some bugs in the `Ethernet calibrator`.
1. there is an empty debug string: `DEBUG] Left_Arm_Calibrator : Joints calibration order:      ` 
2. the `checkHWFault` function performed a loop on the joints in (0, totJointsToCalibrate) range instead of on the list containing the required joints.
3. the return value of `checkHWFault` function was ignored.
We fixed them in this way:
1. 
2. the loop in performed on the elements containing in the list of joints to calibrate 
| Before | After |
|---|---|
| ![Screenshot from 2023-04-27 12-06-07](https://user-images.githubusercontent.com/4233231/234831009-d1b75d41-0b85-4ecb-b066-d12b18e35c30.png) | ![Screenshot from 2023-04-27 …
> EthCalibrator: fixed CheckHwFault

- src/tools/iCubSkinGui/plugin/CMakeLists.txt
This PR fixes #867.
cc @simeonedussoni
> Fix CMake for `SkinGui` w/ Fingertips Mk1.1

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
Now we can use the `mrie` name in the configuration file.
This encoder is used for the new joints.
I already tested this PR on the medium joint setup and it works together.
This code needs the updated `icub-firmware-shared` at version `1.34.2`.
I'll open a new PR for it.
> Added the mrie encoder name in the parser of motion control service.

- app/faceExpressions/scripts/faceExpressions.xml.template
With the last releases, the old `serialport` device used for running the faceExpressions.xml application could not be found (see figure below) 
In this way, it is replaced with the new `serialPort_nws_yarp` which runs properly on iCubGenova11.
> Change the device running faceExpressions from serialport to serialPort_nws_yarp

- src/libraries/icubmod/embObjFTsensor/embObjFTsensor.cpp
- src/libraries/icubmod/embObjFTsensor/eo_ftsens_privData.cpp
- src/libraries/icubmod/embObjLib/serviceParser.cpp
It fixes #873.
I will test it on the robot before merging.
> embObjFTSensor: make it handle strain board

- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.cpp
- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.h
- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.h
- src/libraries/icubmod/dragonfly2/winnt/FirewireCameraDC1394-DR2_2.h
- src/tools/frameGrabberGui2/dc1394SliderBase.h
- src/tools/frameGrabberGui2/dc1394thread.h
It fixes #864
In YARP 3.5.0 the `FrameGrabberInterfaces` header has been deprecated, but the interfaces included not, except for very old interfaces such as `IFrameGrabber` and `iFrameGrabberRgb`, that were implemented but not used by anyone. The `frameGrabber_nws_yarp` uses the "new" interfaces.
> dragonfly2: remove deprecated interfaces

- app/faceExpressions/CMakeLists.txt
- app/faceExpressions/scripts/faceExpressions.xml.template
> Fixed context handling for faceExpressions

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
This PR brings an update to the current version of `calibration type 14`. Specifically the following things have changed:
- FAP calibration data are not passed anymore only through the `CALIBRATION` group in the `POS` service configuration file but the final correct values should be defined at `parameters 3, 4 and 5 ` of the calibration configuration file as defined in the documentation. Moreover in this file `offset` and `rotation` values should be passed in `icubDegrees`. 
- Anyway, `CALIBRATION` group in MC and POS is still kept for debugging reasons. Values in calibrators will override the one configured initially by the POS service.
- Then, with this update the calibration will do the following steps:
- calibrate the FAP absolute encoder
- bring the motor pulley to the hard stop
- …
> Calibration type 14 update on calibration value parser

- src/libraries/icubmod/embObjMultipleFTsensors/embObjMultipleFTsensors.cpp
https://github.com/robotology/icub-main/pull/871 introduce one critical bug in the `embObjMultipleFTsensors` YARP device: as for some reason the default value of [checkUpdateTimeoutFlag_](https://github.com/robotology/icub-main/blob/v2.2.0/src/libraries/icubmod/embObjMultipleFTsensors/embObjMultipleFTsensors.h#L93) is false, no check if the sensor is in timeout is done. As the assigned of the status to `MAS_OK` only happens if the check for timeout is done, what happened since https://github.com/robotology/icub-main/pull/871 is that the sensor always returned the initial status `MAS_WAITING_FOR_FIRST_READ`, even if a first read already arrived.
This resulted in yarprobotinterface logs flooded by messages like:
~~~
4631,378732	ERROR	yarp.device.multipleanalogsensorsserver		Failure in …
> embObjMultipleFTsensors: Set the status to MAS_OK even if the timeout check is disabled

- src/tools/FirmwareUpdater/.vscode/settings.json
- src/tools/FirmwareUpdater/calibrationwindow.cpp
- src/tools/FirmwareUpdater/customspinbox.cpp
- src/tools/FirmwareUpdater/main.cpp
- src/tools/FirmwareUpdater/mainwindow.cpp
As per title, this PR updates the checks during the firmwareupdater execution to allow for the `Calibrate` functions to work.
> Update firmwareupdater to handle calibration functions for strain2

- src/tools/frameGrabberGui2/dc1394thread.cpp
> FrameGrabberGui2: fix after remote_grabber deprecation

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/CMakeLists.txt
- src/libraries/icubmod/embObjLib/FeatureInterface.cpp
- src/libraries/icubmod/embObjLib/FeatureInterface.h
- src/libraries/icubmod/embObjLib/IethResource.cpp
- src/libraries/icubmod/embObjLib/IethResource.h
- src/libraries/icubmod/embObjLib/diagnosticInfo.cpp
- src/libraries/icubmod/embObjLib/diagnosticInfo.h
- src/libraries/icubmod/embObjLib/diagnosticInfoFormatter.cpp
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
- src/libraries/icubmod/embObjLib/diagnosticLowLevelFormatter.h
- src/libraries/icubmod/embObjLib/diagnosticLowLevelFormatter_hid.h
- src/libraries/icubmod/embObjLib/ethManager.cpp
- src/libraries/icubmod/embObjLib/ethManager.h
- src/libraries/icubmod/embObjLib/protocolCallbacks/EoProtocolMN_fun_userdef.c
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
In this PR, I created the new diagnostic formatter and a parser for each diagnostic message class.
The goal of this work is to start to improve the robot's embedded diagnostic making it more human-readable.
I developed a formatter that is called on the reception of a diagnostic message.
Depending on the diagnostic class (Motioncontrol, Hardaware,Configuartion, etc ) the formatter calls the propper parser.
**Class Diagram**
The `DefaultParser` prints the diagnostic information as now.
**Sequence Diagram:  `yarprobotinterface `receives an error belonging to the motion-control class**
**NOTE**
If an unknown error is received or the parser doesn't know how to parse the message the default parser is invoked: it prints the massage like it now.
If you (as a developer) want to change the contents …
> Make embedded diagnostic more human readable

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
This PR introduces a temporary fix to the hw fault check in order to do not have problem with YRI restarting on joints that mounts encoders which are highly sensible to disturbances, such as the MAIS on the fingers of iCub.
The reason to introduce this change and to define it temporary are here defined:
- previously with [this PR](https://github.com/robotology/icub-main/pull/866) the check on the hw faults has been enabled. As a matter of fact we realized that in that code section mentioned in the PR the logic of the code was erroneous, because the check of the faults is never taken into account, but the operations can continue independently on the fact that a fault is present or not. Therefore, it has been decided to wrap the method in a if condition and stop the calibration procedure if …
> Temporary workaround for MAIS finger problem

- src/libraries/icubmod/embObjLib/ethBoards.cpp
- src/libraries/icubmod/embObjLib/ethBoards.h
This PR should fix #840. 
Together with @sgiraz, we found out that the `double free or corruption` error that was retrieved when running `yarpdev --list` may occur in `eth::EthBoards` class. In particular, it seems that the destructor of this class is responsible for destroying some members of this class, but then another function is trying to free memory that was already freed. 
@marcoaccame what do you think about it? Could you please have a look?
> Fix 'double free or corruption' error on yarpdev --list

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjBattery/CMakeLists.txt
- src/libraries/icubmod/embObjBattery/embObjBattery.cpp
- src/libraries/icubmod/embObjBattery/embObjBattery.h
- src/libraries/icubmod/embObjLib/ethResource.cpp
- src/unittest/testDeviceCanBatterySensor.cpp
This PR allow the user to see debug message when BAT status change in YRI
Moreover status is sent as an `int32_t` to the specific BAT or BMS port
> Status passed to embObjBattery.cpp

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
Since, now the procedure for setting the control mode of the joints has been clarified, it is correct to re-enable the check of the hw faults before proceeding with the calibration procedure of the jonts.
> Re-enabled the check of the hw fault before proceeding with calibration

- src/modules/gravityCompensator/main.cpp
As per title.
In the main.cpp of the `gravityCompensator` module, I found two if statements with the same condition but they do the exact opposite.
> Fix typo in gravityCompensator main

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
In this PR I fixed a bug related to the formatting of overflow timing of the embedded loop.
In addition, I force icub-main to use the last version of icub-fw-shared (1.36.2).
This Pr has been tested on the wrist MK2.1 setup
> Fix diagnostic overflow time + bumped icub-firmware-share to 1.36.2

- src/libraries/icubmod/bcbBattery/bcbBattery.h
See https://github.com/robotology/robotology-superbuild/issues/1536.
Requires a yarp tag > 3.8.1 and that #903 is merged beforehand.
Put in draft until the conditions are met.
> Fix `BATTERY_OK_STANDBY` typo

- src/doc/cmake_usage.dox
- src/modules/actionsRenderingEngine/CMakeLists.txt
- src/modules/camCalib/CMakeLists.txt
- src/modules/camCalibWithPose/CMakeLists.txt
- src/modules/dualCamCalib/CMakeLists.txt
- src/modules/motionCUT/CMakeLists.txt
- src/modules/templatePFTracker/CMakeLists.txt
- src/tools/depth2kin/CMakeLists.txt
- src/tools/stereoCalib/CMakeLists.txt
`OpenCV_LIBS` is the variable documented in official OpenCV docs (https://docs.opencv.org/4.x/db/df5/tutorial_linux_gcc_cmake.html). `OpenCV_LIBRARIES` was a YCM extension, that is going to be deprecated (see https://github.com/robotology/ycm/pull/434).
> CMake: Use OpenCV_LIBS instead of OpenCV_LIBRARIES as documented in official OpenCV docs

- src/libraries/icubmod/bcbBattery/bcbBattery.h
Fix compilation with YARP 3.9 while retaining compatibility with YARP 3.8.1 .
> bcbBattery: Fix compilation with YARP 3.9.0

- src/libraries/learningMachine/include/iCub/learningMachine/DatasetRecorder.h
- src/libraries/learningMachine/include/iCub/learningMachine/FixedRangeScaler.h
- src/libraries/learningMachine/include/iCub/learningMachine/IFixedSizeLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/IFixedSizeTransformer.h
- src/libraries/learningMachine/include/iCub/learningMachine/IMachineLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/IScaler.h
- src/libraries/learningMachine/include/iCub/learningMachine/ITransformer.h
- src/libraries/learningMachine/include/iCub/learningMachine/LSSVMLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/LinearGPRLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/LinearScaler.h
- src/libraries/learningMachine/include/iCub/learningMachine/Normalizer.h
- src/libraries/learningMachine/include/iCub/learningMachine/RLSLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/RandomFeature.h
- src/libraries/learningMachine/include/iCub/learningMachine/ScaleTransformer.h
- src/libraries/learningMachine/include/iCub/learningMachine/SparseSpectrumFeature.h
- src/libraries/learningMachine/include/iCub/learningMachine/Standardizer.h
- src/modules/camCalib/include/iCub/ICalibTool.h
- src/modules/camCalib/include/iCub/PinholeCalibTool.h
- src/modules/camCalib/include/iCub/SphericalCalibTool.h
- src/modules/camCalibWithPose/include/iCub/ICalibTool.h
- src/modules/camCalibWithPose/include/iCub/PinholeCalibTool.h
- src/modules/camCalibWithPose/include/iCub/SphericalCalibTool.h
- src/modules/dualCamCalib/include/iCub/ICalibTool.h
- src/modules/dualCamCalib/include/iCub/PinholeCalibTool.h
- src/modules/dualCamCalib/include/iCub/SphericalCalibTool.h
- src/modules/learningMachine/QUICKSTART
- src/modules/learningMachine/include/iCub/learningMachine/IEventListener.h
- src/modules/learningMachine/include/iCub/learningMachine/IPortEventListener.h
Partial fix for https://github.com/robotology/icub-main/issues/922 .
> Remove use of `yarp::os::IConfig` interface

- .github/workflows/ci.yml
- src/libraries/icubmod/bcbBattery/bcbBattery.h
I suspect https://github.com/robotology/icub-main/pull/920 actually broke compilation with YARP 3.8.1 (based on robotology-superbuild CI), but we did not realized this as the CI does not actually compile the bcbBattery device.
> CI: Enable compilation of bcbBattery device

- src/libraries/icubmod/canBusFtSensor/CanBusFtSensor.cpp
- src/libraries/icubmod/canBusFtSensor/CanBusFtSensor.h
- src/libraries/icubmod/embObjFTsensor/embObjFTsensor.cpp
- src/libraries/icubmod/embObjFTsensor/embObjFTsensor.h
- src/libraries/icubmod/embObjMais/embObjMais.cpp
- src/libraries/icubmod/embObjMais/embObjMais.h
They are canBusFtSensor, embObjFTsensor, embObjMais
It fixes #919
> Remove IAnalogSensor interface from the devices ported to the new interfaces

- src/libraries/icubmod/embObjLib/CMakeLists.txt
I follow the style of how libraries are installed in icub-main, for example https://github.com/robotology/icub-main/blob/92430ce9c1a249964f99382da3df7a91537fd42e/src/libraries/iKin/CMakeLists.txt#L61 .
> Fix installation directory of ethResources shared library on Windows

- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
This PR enables the `eomcParser` to parse all parameters within `TRQ_PID_OUTPUT_CURR`, even if `kbemf` is missing.
cc @pattacini @Nicogene @isorrentino @DanielePucci
> Bugfix `kbemf` set to 0 by default when not found

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjLib/serviceParser.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
This PR belongs to a set of five PRs on `icub-firmware`, `icub-firmware-shared`, `icub-firmware-build`, `icub-main` and `robots-configuration`.
They introduce a new MC service  that supports  actuators located on the second core of the new dual core ETH boards that run the outer control loop at 1 ms.  So far the only dual core board we use is the `amc` which runs on the first CM7 core and uses an actuator board on its CM4 core: the `amc2c`. 
See https://github.com/robotology/icub-firmware/pull/474 for details
- https://github.com/robotology/icub-firmware/pull/474
- https://github.com/robotology/icub-firmware-shared/pull/93
- https://github.com/robotology/icub-firmware-build/pull/141
- https://github.com/robotology/robots-configuration/pull/623
> The `amc` board uses `ICC` and `CAN` to move the wrist of `ergoCub`

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjBattery/embObjBattery.cpp
- src/libraries/icubmod/embObjBattery/embObjBattery.h
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
Changes in this PR:
- Add to diagnostic parser overheating error
- Update embObjBattery
- Re-elaborate status bat-bms using uint16_t as datatype and using string_view instead of string for status messages 
- Update bat reading values adding total absorbed current in BAT and adjusting limits for BAT SoC calculation
- Fix datatype in diagnostic to be aligned by raw value datatype Set value of battery charge to NaN if equal to zero 
- Update MINIMUM_REQUIRED_icub_firmware_shared_VERSION to 1.38.2
Related to:
- https://github.com/robotology/icub-firmware-build/pull/146
- https://github.com/robotology/icub-firmware/pull/487
- https://github.com/robotology/icub-firmware-shared/pull/95
> Add to diagnostic parser overheating error and Update embObjBattery

- src/libraries/icubmod/embObjLib/diagnosticInfoFormatter.cpp
- src/libraries/icubmod/embObjLib/diagnosticLowLevelFormatter_hid.h
- src/libraries/icubmod/embObjLib/ethBoards.cpp
- src/libraries/icubmod/embObjLib/ethBoards.h
This PR fix the problem seen on windows when launching the `yarprobotinterface` where weird characters were shown on the logs. 
This was due due to a not correct initialization of the variables of the struct `ethboardProperties_t` used by the `LUT` array in `ethBoards.h`. This bad initialization was breaking the copying of new `std::string` vars in the variable `name` of that struct.
Now as shown in the related issue here: https://github.com/robotology/icub-main/issues/913, the prints are fine.
> Fix constructor and destructor of `eth::EthBoards` class

- src/libraries/icubmod/embObjLib/diagnosticInfo.h
- src/libraries/icubmod/embObjLib/ethParser.h
This fix compilation of icub-main on Ubuntu 24.04 with compilers and libraries provided by apt (see https://github.com/robotology/robotology-superbuild/issues/1641#issuecomment-2081181207). Probably everything worked in earlier distributions due to transitive includes.
> Fix missing cstdint include in headers that use uint16_t and uint32_t types

- bindings/icub.i
Without this, compilation with SWIG 4.2.1 fails with:
~~~
[100%] Building CXX object bindings/CMakeFiles/_icub_python.dir/CMakeFiles/_icub_python.dir/icubPYTHON_wrap.cxx.o
/home/traversaro/robotology-superbuild/build/src/ICUB/bindings/CMakeFiles/_icub_python.dir/icubPYTHON_wrap.cxx: In function ‘PyObject* _wrap_waveletIntegrand(PyObject*, PyObject*)’:
/home/traversaro/robotology-superbuild/build/src/ICUB/bindings/CMakeFiles/_icub_python.dir/icubPYTHON_wrap.cxx:26621:22: error: ‘waveletIntegrand’ was not declared in this scope; did you mean ‘_wrap_waveletIntegrand’?
26621 |     result = (double)waveletIntegrand(arg1,arg2);
|                      ^~~~~~~~~~~~~~~~
|                      _wrap_waveletIntegrand
make[2]: *** [bindings/CMakeFiles/_icub_python.dir/build.make:76: …
> icub.i: Fix compatibility with SWIG 4.2.1

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
This is a simple fix that should make the calibrator info clearer.
cc @MSECode
> Fix a print in parametricCalibratorEth

- src/libraries/icubmod/embObjLib/abstractEthResource.h
- src/libraries/icubmod/embObjLib/diagnosticInfo.cpp
- src/libraries/icubmod/embObjLib/ethResource.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
Completing the work done in https://github.com/robotology/icub-main/issues/959, the spikes in the temperature readings are 
now filtered by software.
This means that if the delta between current and previous temperature is higher than a threshold (which is currently defined in sw and by default is 20 Celsius degree) that new temperature read is considered as a spike and therefore, even if its value is higher than the `warning temperature threshold` or the `error temperature threshold`, it is discarded and not considered and the previous temperature is not updated.
Moreover, we have added to the `Watchdog` class a method for setting the threshold, regarding the maximum number of erroneous values read before sending error or warning, depending on the transmission rate of the ethernet …
> Update filtering of spikes in temp reading

- src/libraries/icubmod/embObjLib/ethBoards.cpp
This PR fix the bug described here: https://github.com/robotology/icub-main/issues/962 that caused a core dumping when closing the resources for a specific device (when multiple devices are enabled)
Basically, at the removal of the first resource we were basically going to remove all the open resources.
> Fix bug when removing ethResource from LUT in clear method

- src/libraries/icubmod/embObjLib/ethBoards.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
This PR related to the issue https://github.com/robotology/icub-firmware/issues/497, changes the default option for the `verbose` option in `eomcParser.cpp` from the value of `1` to `0`.
In this manner when the option is not defined in the `2FOC` group in the robot configuration files the CAN and the YRI are not flooded with debug messages as shown in the mentioned issue.
> Set verbose elective option in 2FOC group to zero by defualt

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
This PR adds a guard for preventing the division by 0
> Fix floating point exception in `embObjMotionControl` 

- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
This PR modify slightly the parsing of the aksim2 diagnostic errors adding the number of jomo (joint-or-motor) in board and the number of errors of each type we got in the predefined time.
This is linked to the modifications integrated in https://github.com/robotology/icub-firmware/pull/500
> Modify the parsing of the aksim2 diagnostic error

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
- src/libraries/icubmod/embObjLib/ethParser.cpp
- src/libraries/icubmod/embObjLib/ethResource.cpp
This PR introduces the xml parsing of configuration of the diagnostics associated to the execution loop and its transmission towards the `ETH` boards.
In particular, it will be possible to:
- enable / disable the diagnostics about execution overflow of the `RX`, `DO `and `TX `phases. The default is enabled.
- enable / disable the diagnostics about statistics of the  `RX`, `DO `and `TX `phases. It will be reported minimum, average and maximum durations of the phases over a period configurable between 1 and 600 seconds. The default is disabled.
This latter feature is particularly useful when one wants to measure the effective duration of `RX`, `DO` and `TX` phases for a particular board over a period of time. As shown later It is possible to activate the section `LOGGING.PERIODIC` and set …
> Runtime configuration of diagnostics related to the RX-DO-TX phases

- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
This change is related to https://github.com/robotology/icub-firmware/pull/503, particularly to the improvements of the quadrature encoder diagnostic. 
cc @MSECode
> Improved the diagnostic of quadrature encoder

- src/libraries/icubmod/embObjLib/ethReceiver.cpp
In the `embObjLib`, the `ethReceiver` is the thread dedicated to receive the UDP messages sent by the ETH boards (such as EMS, MC4_PLUS). 
On Linux and macOS, this socket is set in non-blocking mode by the code:
~~~cxx
int flags = 0;
#ifndef WIN32
flags |= MSG_DONTWAIT;
#endif
~~~
in https://github.com/robotology/icub-main/blob/v2.6.2/src/libraries/icubmod/embObjLib/ethReceiver.cpp#L177-L180 .
However, there is no such flag on Windows, so in the Windows case the `recv` call in https://github.com/robotology/icub-main/blob/v2.6.2/src/libraries/icubmod/embObjLib/ethReceiver.cpp#L200 was actually blocking. I am not super-expert of this part of code, so I am not sure what was the effect of the code being non-blocking there on Windows, but for sure I experienced a related problem: when I was …
> embObjLib: in ethReceiver set receiving thread as non-blocking also on Windows

- bindings/CMakeLists.txt
- src/libraries/learningMachine/standalone/CMakeLists.txt
- src/modules/learningMachine/standalone/CMakeLists.txt
- src/tools/embObjProtoTools/boardTransceiver/CMakeLists.txt
- src/tools/embObjProtoTools/embObjProto_debugParser/CMakeLists.txt
- src/tools/embObjProtoTools/nvListPrinter/CMakeLists.txt
- src/tools/emsBackDoorManager/CMakeLists.txt
- src/unittest/CMakeLists.txt
All these calls in sub-folders only make sense if the subfolder could be built as an indipendent project (i.e. creating a build folder in just the subfolder), but that is not the case, so they only create possible confusion if one wanted to change the arguments passed to `cmake_minimum_required`, so I think it is better to just remove them.
> Remove cmake_minimum_required calls in non-root directories

- CMakeLists.txt
I recently had problem in compiling icub-main in a conda environment with Python 3.10 installed while the system (Ubuntu 24.04) had Python 3.12 installed. This happened as the old (pre-3.15) behaviour of CMake was to always  find the most recent Python version, instead of getting the highest in the path (see https://cmake.org/cmake/help/latest/policy/CMP0094.html).
The problem can be solved without raising the minimum required CMake by setting the `CMP0094` policy to `NEW`, but I think it was good idea to directly raise the policy_max (i.e. the version used for the policies of CMake) argument of `cmake_minimum_required` to 3.28.
> Bump policy_max argument of cmake_minimum_required to 3.28

- bindings/CMakeLists.txt
- bindings/icub.i
Fix https://github.com/robotology/icub-main/issues/984: https://github.com/robotology/icub-main/commit/c1b007ac630b687bc6e52b8f1abd252c427a5fed
Permit to build bindings as standalone projects, to easily compile separately C++ library and Python bindings (useful to support easily multiple Python versions). Furtheremore, cleanup the CMake structure by using [`SWIG_USE_TARGET_INCLUDE_DIRECTORIES`](https://cmake.org/cmake/help/latest/module/UseSWIG.html#properties-on-targets) instead of manually passing directories via `include_directories`: https://github.com/robotology/icub-main/commit/1f02858bb678f7fc9de45e0ce4c890b3398caf69
Remove references to iDyn library (that anyhow was not wrapped in bindings): https://github.com/robotology/icub-main/commit/8eac01933c0df534a5c0eff51c409f7fc99808cb
> Fix python bindings and related bindings cleanup

- bindings/CMakeLists.txt
Linking to `Python::Python` results in a segfault on module loading on macos.
> Link Python bindings to Python::Module and not Python::Python to prevent Python bindings segfault on macOS

- bindings/icub.i
`SWIG_Python_AppendOutput` was never meant to be used and changed the signature in SWIG 4.3.0, `SWIG_AppendOutput` is the function that should be used and is also present in older SWIG releases, see https://sourceforge.net/p/swig/mailman/message/58825934/ and https://github.com/numpy/numpy/pull/27579 for context.
> Replace SWIG_Python_AppendOutput with SWIG_AppendOutput for SWIG 4.3.0 compatibility

- .github/workflows/ci.yml
Fixes #988
Update CI configuration to use Ubuntu 24.04 and custom SWIG 4.2.1
* Change the CI configuration in `.github/workflows/ci.yml` to use `ubuntu-24.04` instead of `ubuntu-22.04`.
* Add steps to install a custom build of SWIG 4.2.1 for Ubuntu 24.04.
* Remove the step to install SWIG via `sudo apt install`.
* Ensure the custom SWIG 4.2.1 is used for the build process on Ubuntu 24.04.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/robotology/icub-main/pull/999?shareId=a324a996-0248-44c6-9f6f-307b95f6081f).
> Fix CI failure with SWIG::Python on Ubuntu 24.04

- .github/workflows/ci.yml
- CMakePresets.json
I recently heard about a failure mode of an installation that failed as the required option `ENABLE_icubmod_embObjPOS` was not enabled. While the corresponding option was indeed enabled in the superbuild (see https://github.com/robotology/robotology-superbuild/pull/1340), I realized that the long list of devices that should be enabled when icub-main is used on a robot (iCub, ergoCub, R1) was indeed hardcoded in several places:
* https://github.com/robotology/robots-configuration/blob/d7dd20a2ae04fdd7f83046bb96ff7e6a1b1e2bdb/tests/dockerfiles/Dockerfile#L102
* https://github.com/icub-tech-iit/documentation/blob/98ca2cb07e0d9bc07990d438e15a73b328736e61/docs/sw_installation/icub_head_manual.md?plain=1#L242
* https://github.com/robotology/robotology-vcpkg-ports/blob/efd91793e121185c1c67e49fe7d …
> Add CMakePresets.json and robot preset

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/IethResource.cpp
- src/libraries/icubmod/embObjLib/IethResource.h
- src/libraries/icubmod/embObjLib/diagnosticInfoFormatter.cpp
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
- src/libraries/icubmod/embObjLib/diagnosticLowLevelFormatter_hid.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
Make for abs encoders (at joint) are more general
Moroever, now we show the abs encoder type too in the diagnostic message, solving the issue: https://github.com/robotology/icub-firmware/issues/533
Related to: 
- https://github.com/robotology/icub-firmware-shared/pull/102
- https://github.com/robotology/icub-firmware/pull/540
> Update diagnostic to make it more general

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
This PR fixes some lines of code:
- First of all we removed the debug lines for calibration14 in embObjMotionControl::setCalibrationParametersRaw()
- Moreover we fix the timestamps in log for temperature errors using relative time from construction of embObjMC device 
- Finally we change yError to yWarning when failing to read temperatures considering that in that case the system won't stop
cc: @valegagge
> Remove debug lines for calibration14 and fix temperatures timestamp

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
The yarprobotinterface parser is now able to read LuGre friction model parameters from robot configuration files.
> Added LuGre friction model parameters to protocol

- src/tools/FirmwareUpdater/firmwareupdatercore.cpp
- src/tools/FirmwareUpdater/firmwareupdatercore.h
- src/tools/FirmwareUpdater/mainwindow.cpp
The `FirmwareUpdater` now recognise the `amcfoc` application names correctly.
> `FU` recognise `amcfoc` applications name

- src/libraries/icubmod/embObjIMU/eo_imu_privData.h
Fixes #1009.
Thanks @traversaro
> Avoid using `typedef struct` in C++

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.h
This pull request introduces the first MVP for a new calibrator. The key changes include setting safe PWM limits only to joints that fail calibration, defining a new MAINTENANCE mode to enalble `skipRecalibration` feature and other minor changes.
Moreover, we create a new struct in the firmware for this maintenance mode in order to collect in a single group current and upcoming flags and data related to this mode. Then we fix the code  preventing errors when joints go to zero position during calibration with `skipRecalibration` enabled.
Another small change that we have added is modifying the control mode requests in `embObjMotionControl::calibrationDoneRaw()` from remote to local RAM call
Finally we have aligned dependencies to `icub_firmware_shared` protocol v1.43.0. 
The main goal of …
> MVP1 and MVP2 for new calibrator

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
As per title, this PR aims for a tiny QoL improvement to avoid flooding the yarprobotinterface terminal when using clients (e.g. `robometry`) that periodically call interfaces with methods deprecated or not implemented.
> embObjMotionControl: switch to log error once to avoid flooding terminal for non-implemented and deprecated functions

- src/libraries/icubmod/embObjLib/serviceParser.cpp
As per title, this further check will allow the group [`MAIS`](https://github.com/robotology/robots-configuration/blob/1d292659dc4777b5d5c20d2a702fe8968ea9f8ef/iCubGenova11/hardware/motorControl/right_arm-eb28-j8_11-mc_service.xml#L29-L31) within the motorControl service XML file to be parsed only when the device is of type `eomn_serv_MC_mc4plusmais`, otherwise will be ignored by the parser.
> Add further check for eomn_serv_MC_mc4plusmais device

- src/tools/fineCalibrationChecker/CMakeLists.txt
Multiple-config CI builds of the robotology-superbuild started failing with error:
~~~
2025-06-30T12:46:04.2371322Z   -- Found YARP: C:/robotology/robotology/lib/cmake/YARP (found version "3.12.0+1-20250604.5+git285f6317e")
2025-06-30T12:46:04.2757524Z   CMake Error at C:/robotology-superbuild/build/src/ICUB/iCubDev/iCubDevConfig.cmake:21 (include):
2025-06-30T12:46:04.2758248Z     include could not find requested file:
2025-06-30T12:46:04.2758639Z   
2025-06-30T12:46:04.2758905Z       C:/robotology-superbuild/build/src/ICUB/iCubDev/iCubDevTargets.cmake
2025-06-30T12:46:04.2759257Z   Call Stack (most recent call first):
2025-06-30T12:46:04.2759602Z     C:/robotology/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
2025-06-30T12:46:04.2760039Z …
> Remove find_package(iCubDev) from fineCalibrationChecker

- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
Down in robotology-superbuild CI, I saw this evening errors like:
~~~
2025-07-08T18:34:50.8721830Z /Users/runner/work/robotology-superbuild/robotology-superbuild/src/ICUB/src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp:559:39: error: non-constant-expression cannot be narrowed from type 'eObus_t' to 'uint8_t' (aka 'unsigned char') in initializer list [-Wc++11-narrowing]
2025-07-08T18:34:50.9726850Z   559 |             eOlocation_t location = { static_cast<eObus_t>(bus), 0, address};
2025-07-08T18:34:51.0729820Z       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
2025-07-08T18:34:51.1734290Z /Users/runner/work/robotology-superbuild/robotology-superbuild/src/ICUB/src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp:559:39: note: insert an explicit cast to …
> diagnosticInfoParsers: Remove intermediate upcast to int in uint8_t to uint8_t assignment

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
I've added configurable timeouts for PWM, current and torque setpoints, and timeout for torque feedback.
The timeout for torque measure was already implemented, but it wasn't  configurable.
Only the velocity timeout is mandatory in configurable files because (same as before), and the other parameters are optional with default value = 100 ms to maintain compatibility. A value of 0 disables the watchdog.
In order to use the yarpmotorgui in PWM, current and torque modes these values must be set to 0 in the configuration files.
> Timeout parameters for PWM, current and torque setpoints added to protocol

- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjLib/serviceParser.h
- src/libraries/icubmod/embObjMais/embObjMais.cpp
- src/libraries/icubmod/embObjPOS/embObjPOS.cpp
- src/libraries/icubmod/embObjPOS/embObjPOS.h
This PR brings the following changes:
- POS switch parent class from IAnalogSensor to IEncoderArrays with redefinition of derived classes to match with
multipleanalogsensorsremapper and multipleanalogsensorsserver 
- we add private function for remapping wrapped sensors index with index from boards data
- we add `sensorName` to `servConfigPOS_t` that might be useful if we wanna change the POS remapper strategy passing from one remmaper per service open to one remapper per all joints that mounts a FAP encoder
It has been tested on ergoCub001
> POS service refactoring
