robotology/icub-main

- src/core/iCubInterface/RobotInterfaceRemap.cpp
- src/libraries/iCubVis/salience/src/CvFaceSalience.cpp
- src/libraries/icubmod/canBusInertialMTB/CanBusInertialMTB.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.h
- src/libraries/icubmod/canBusSkin/CanBusSkin.cpp
- src/libraries/icubmod/canBusVirtualAnalogSensor/CanBusVirtualAnalogSensor.cpp
- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.cpp
- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.cpp
- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.h
- src/libraries/icubmod/dragonfly2/winnt/FirewireCameraDC1394-DR2_2.cpp
- src/libraries/icubmod/dragonfly2/winnt/FirewireCameraDC1394-DR2_2.h
- src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.cpp
- src/libraries/icubmod/embObjLib/FeatureInterface.cpp
- src/libraries/icubmod/embObjLib/ethManager.cpp
- src/libraries/icubmod/embObjLib/ethResource.cpp
- src/libraries/icubmod/embObjLib/hostTransceiver.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjSkin/embObjSkin.cpp
- src/modules/gravityCompensator/main.cpp
- src/modules/skinManager/src/skinManager.cpp
- src/modules/wholeBodyDynamics/main.cpp
- src/simulators/iCubSimulation/odesdl/iCub.cpp
- src/simulators/iCubSimulation/odesdl/iCub_Sim.cpp
- src/tools/canLoader/canLoader/main.cpp
- src/tools/canLoader/canLoaderLib/ethDriver.h
- src/tools/controlBoardDumper/main.cpp
improved logs of icub-main modules (adding yWarning(), yError() etc)
> improved log of icub-main modules 

- app/robots/vizzy/vizzy-cluster-at-deepthought.xml
- app/robots/vizzy/vizzy-cluster-at-icub-laptop.xml
- app/robots/vizzy/vizzyStartup.xml
- app/robots/vizzy/ymanager.ini
xml tested on deepthought and ready for icub-laptop.
> adding xml definition for gyarpmanager and cluster manager for vizzy

- app/robots/vizzy/camera/dragonfly2_config_left.ini
- app/robots/vizzy/camera/dragonfly2_config_left_ball_tracker.ini
- app/robots/vizzy/camera/dragonfly2_config_left_bayer_320_240.ini
- app/robots/vizzy/camera/dragonfly2_config_left_bayer_640_480.ini
- app/robots/vizzy/camera/dragonfly2_config_right.ini
- app/robots/vizzy/camera/dragonfly2_config_right_bayer_320_240.ini
- app/robots/vizzy/camera/dragonfly2_config_right_bayer_640_480.ini
- app/robots/vizzy/hardware/left_arm.xml
- app/robots/vizzy/kinematics_left_arm.ini
- app/robots/vizzy/kinematics_right_arm.ini
- app/robots/vizzy/vizzyEyes320x240.ini
files for cartesian controller and solver
> cameras guid updated and added camera calibration files and DH params

- app/robots/vizzy/demoBallTrackingGrasping_IIT_ISR_Vizzy_visual_deepthought.xml
- app/robots/vizzy/leftAndRightCamerasWithVisualization_deepthought.xml
- app/robots/vizzy/leftCameraForBallTracker.xml
- app/robots/vizzy/vizzyStartup.xml
> added application xml files for running cameras remotely and ball tracker

- app/robots/iCubGenova01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubGenova01/hardware/motorControl/icub_right_hand.xml
Configuration taken from iCubGenova03.
@randaz81
> Updated iCubGenova01 config files

- app/robots/iCubDarmstadt01/hardware/skin/left_arm-ems2-skinSpec.xml
- app/robots/iCubDarmstadt01/hardware/skin/right_arm-ems4-skinSpec.xml
> iCubDarm01: skin configuration update

- app/iCubCluster/scripts/icub-cluster.py
@lornat75, I forgot to change this.
> Forgot to remove a temporary debug script on the remote pc

- app/robots/iCubLisboa01/iCubStartup.xml
...due to https://github.com/robotology/icub-main/commit/89d9bd26fd3ba9f561cbdabe9389953080c162b7
See also https://github.com/robotology/icub-main/commit/76cb3ad0d59f86c38edd578f64e1a4a167330025
> [iCubLisboa01]: iCubStartup change

- app/robots/vizzy/icub-cluster-at-vizzy-desktop.xml
- app/robots/vizzy/stereoGazeSelection.xml
Application file for running the cluster on vizzy-desktop
Application file for running stereo gaze selection
> [vizzy] Application files added

- app/robots/vizzy/vizzyStartupWithROS.xml
added xml file that allows to run modules for Vizzy's visualization in Rviz
> added xml file that allows to run modules for Vizzy's visualization 

- app/robots/iCubLisboa01/skinGuiAll.xml
New skin gui XML launcher for iCubLisboa01.
> [iCubLisboa01]: new skin gui XML launcher

- app/robots/iCubLisboa01/calibrators/head_calib.xml
- app/robots/iCubLisboa01/calibrators/left_arm_calib.xml
- app/robots/iCubLisboa01/calibrators/left_hand_calib.xml
- app/robots/iCubLisboa01/calibrators/left_leg_calib.xml
- app/robots/iCubLisboa01/calibrators/right_arm_calib.xml
- app/robots/iCubLisboa01/calibrators/right_hand_calib.xml
- app/robots/iCubLisboa01/calibrators/right_leg_calib.xml
- app/robots/iCubLisboa01/calibrators/torso_calib.xml
- app/robots/iCubLisboa01/hardware/VFT/left_arm_virtual_strain.xml
- app/robots/iCubLisboa01/hardware/VFT/left_leg_virtual_strain.xml
- app/robots/iCubLisboa01/hardware/VFT/right_arm_virtual_strain.xml
- app/robots/iCubLisboa01/hardware/VFT/right_leg_virtual_strain.xml
- app/robots/iCubLisboa01/hardware/VFT/torso_virtual_strain.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_head.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_torso.xml
- app/robots/iCubLisboa01/icub_noSkin.xml
- app/robots/iCubLisboa01/robotInterface_noSkin.ini
- app/robots/iCubLisboa01/wrappers/skin/left_arm_skin_wrapper.xml
- app/robots/iCubLisboa01/wrappers/skin/left_hand_inertial_wrapper.xml
- app/robots/iCubLisboa01/wrappers/skin/right_arm_skin_wrapper.xml
- app/robots/iCubLisboa01/wrappers/skin/right_hand_inertial_wrapper.xml
- app/robots/iCubLisboa01/wrappers/skin/torso_skin_wrapper.xml
> [iCubLisboa01]: robotInterface configuration updates

- src/libraries/icubmod/embObjLib/hostTransceiver.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjMotionControl/usrcbk/embObjMotionControl_callback.c
applied changes in status of joints and motors just committed in icub-firmwar-shared
* now we use motion done with a direct ask<> to the relevant board (EMS or MC4).
* using new data structure for pid status but still in legacy form.
> Bigger mc status

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/hostTransceiver.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
- src/tools/simpleClient/main.cpp
now robotInterface detects invalid received udp frames and prints more info if there are errors in sequence number
> Receiver more diagn

- app/robots/iCubLondon01/hardware/motorControl/icub_head.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_torso.xml
1. Fixes errors when starting `robotInterface` because of missing `AxisName` parameters.
2. New calibration for left arm after replacement of tendon
3. New calibration for eyes for better stereo vision
Big thanks to @pattacini and @maxime-petit!
Thanks,
Tobi
/cc @randaz81
> [iCubLondon01] Config update

- src/libraries/iCubDev/include/iCub/DebugInterfaces.h
- src/libraries/iCubDev/src/DebugInterfaces.cpp
- src/libraries/icubmod/canBusInertialMTB/CanBusInertialMTB.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.h
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/skinprototype/skinprototype.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.h
- src/tools/controlBoardDumper/genericControlBoardDumper.cpp
@barbalberto 
3x getRefPositionRaw()
returns the last setPosition (from directPosition)
3x getTargetPositionRaw()
returns the last positionMove (from iPosition)
3x getRefVelocityRaw()
returns the last velocityMove (from iVelocity. Maybe getTargetVelocityRaw is a better name?)
> added new "get reference" methods 

- app/robots/iCubGenova04/calibrators/left_arm-calib.xml
- app/robots/iCubGenova04/calibrators/right_arm-calib.xml
- app/robots/iCubGenova04/hardware/mechanicals/left_lower_arm-ems2-mec.xml
- app/robots/iCubGenova04/hardware/mechanicals/right_lower_arm-ems4-mec.xml
- app/robots/iCubGenova04/hardware/motorControl/left_lower_arm-ems2-mc.xml
- app/robots/iCubGenova04/hardware/motorControl/right_lower_arm-ems4-mc.xml
Commit for configuration files of iCubGenova04
Requires firmware implementation of calibration types 6,7
> new calibration of fingers on ETH robot.

- app/robots/iCubOsaka01/hardware/motorControl/icub_head.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_torso.xml
Added the AxisName parameter for iCubOsaka01
All commits squashed and rebased :)
> iCubOsaka01: Add AxisName parameter

- app/robots/iCubOsaka01/hardware/motorControl/icub_head.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_torso.xml
Added AxisType parameter for iCubOsaka01.
All commits squashed and rebased :)
> iCubOsaka01: add AxisType parameter

- app/robots/iCubLisboa01/hardware/motorControl/icub_head.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_torso.xml
@randaz81, in this PR I applied the same changes recently committed for other robots (```iCubOsaka01```, ```iCubLondon01```) within the #273 discussion.
> [iCubLisboa01]: set AxisName and AxisType

- app/robots/iCubLondon01/hardware/motorControl/icub_head.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_torso.xml
Fix https://github.com/robotology/icub-main/issues/273 for iCubLondon01
@randaz81: Please let me know whether anything is wrong with it, otherwise I'll merge later today.
> [iCubLondon01] Add AxisType parameter

- app/robots/iCubLisboa01/hardware/motorControl/icub_head.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubLisboa01/hardware/motorControl/icub_torso.xml
> [iCubLisboa01]: set motorPwmLimit to CAN value (1333)

- app/robots/iCubLondon01/hardware/motorControl/icub_head.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubLondon01/hardware/motorControl/icub_torso.xml
> [iCubLondon01]: set motorPwmLimit to CAN value (1333)

- app/robots/iCubOsaka01/hardware/motorControl/icub_head.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_arm.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_hand.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_left_leg.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_arm.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_hand.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_right_leg.xml
- app/robots/iCubOsaka01/hardware/motorControl/icub_torso.xml
Adding the motorPwmLimit parameter for iCubOsaka01.
All commits squashed and rebased :)
> [iCubOsaka01] Set motorPwmLimit to CAN value (1333)

- app/robots/iCubLondon01/hardware/motorControl/icub_head.xml
Hi @randaz81,
Please review and merge. Thanks :)!
/cc @jypuigbo: you should apply these changes on `iCubBarcelona01`.
> [iCubLondon01] Lower gains for head V2

- app/robots/iCubLisboa01/hardware/motorControl/icub_head.xml
@randaz81, I followed the recommendation in the following links.
See https://github.com/robotology/icub-support/issues/202 and https://github.com/robotology/icub-main/pull/309
> [iCubLisboa01]: lower gains for head V2

- src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.cpp
- src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.h
- src/libraries/icubmod/embObjLib/FeatureInterface.cpp
- src/libraries/icubmod/embObjLib/FeatureInterface.h
- src/libraries/icubmod/embObjLib/ethManager.cpp
- src/libraries/icubmod/embObjLib/ethManager.h
- src/libraries/icubmod/embObjLib/ethResource.cpp
- src/libraries/icubmod/embObjLib/ethResource.h
- src/libraries/icubmod/embObjLib/hostTransceiver.cpp
- src/libraries/icubmod/embObjLib/hostTransceiver.hpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjSkin/embObjSkin.cpp
- src/libraries/icubmod/embObjSkin/embObjSkin.h
- src/libraries/icubmod/embObjVirtualAnalogSensor/embObjVirtualAnalogSensor.cpp
- src/libraries/icubmod/embObjVirtualAnalogSensor/embObjVirtualAnalogSensor.h
cleaned some more classes used for ETH communication. Now all yarp messages (debug, warning etc.) refer to BOARD w/ is IP address and associated string.
> some changes

- app/robots/iCubLisboa01/hardware/motorControl/icub_right_arm.xml
> [iCubLisboa01]: fix typo in right_arm elbow AxisName

- app/robots/vizzy/robotInterface.ini
- app/robots/vizzy/vizzyStartup.xml
- app/robots/vizzy/vizzyStartupWithROS.xml
- app/robots/vizzy/yarprobotinterface.ini
changed ini file
renamed executable
> [Vizzy] updated configuration for yarprobotinterface

- app/robots/iCubLondon01/hardware/motorControl/icub_left_arm.xml
> [iCubLondon01] Change zeros of left arm

- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
- src/tools/frameGrabberGui2-qt/dc1394slider.cpp
- src/tools/frameGrabberGui2-qt/dc1394sliderwb.cpp
- src/tools/frameGrabberGui2-qt/dc1394thread.cpp
- src/tools/frameGrabberGui2-qt/mainwindow.cpp
Fix handling of some features of usbCamera to be correctly used by FrameGrabberGui
> Fix frame grabber gui usb

- app/robots/iCubLisboa01/iCubStartup.xml
The executable is now called ```yarprobotinterface```. The RPC port is now called ```/icub/yarprobotinterface```.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/325%23issuecomment-215177750%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-04-27T18%3A12%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22titl …
> [iCubLisboa01]: use yarprobotinterface in iCubStartup app

- app/robots/CMakeLists.txt
This typically happens if YARP_ROBOT_NAME is set to `icubGazeboSim` or `coman` .
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/322%23issuecomment-211257126%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/322%23issuecomment-216519495%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/322%23issuecomment-216521161%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/322%23issuecomment-216521238%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/322%23discussion_r59994374%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/322%23discussion_r59995314%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/322%23discussion_r61877158%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Commen …
> [cmake] Fix error in configure if YARP_ROBOT_NAME is not one expected

- app/robots/vizzy/vizzyStartupWithROS_simulator.xml
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/plinioMoreno%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/330%23issuecomment-216884239%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-04T14%3A34%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3798890%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plinio …
> xml file that starts all the contro modules for Vizzy on gazebo

- app/robots/iCubLisboa01/wrappers/FT/left_arm_FT_wrapper.xml
- app/robots/iCubLisboa01/wrappers/FT/left_foot_FT_wrapper.xml
- app/robots/iCubLisboa01/wrappers/FT/left_leg_FT_wrapper.xml
- app/robots/iCubLisboa01/wrappers/FT/right_arm_FT_wrapper.xml
- app/robots/iCubLisboa01/wrappers/FT/right_foot_FT_wrapper.xml
- app/robots/iCubLisboa01/wrappers/FT/right_leg_FT_wrapper.xml
- app/robots/iCubLisboa01/wrappers/MAIS/left_hand_mais_wrapper.xml
- app/robots/iCubLisboa01/wrappers/MAIS/right_hand_mais_wrapper.xml
See https://github.com/robotology/icub-main/commit/387e03c21d32cd53f6fabadeb72443fb04888193#commitcomment-17349280
/cc @randaz81 @Tobias-Fischer @kt10aan
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/333%23issuecomment-217163552%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/333%23issuecomment-217187500%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/333%23issuecomment-217187663%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/333%23issuecomment-217163552%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%21%20We%27ll%20create%20a%20pull%20request%20with%20some%20more%20XML%20changes%20today%20or%20to …
> [iCubLisboa01]: update analog wrapper XML files

- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.cpp
- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.h
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.h
now parametricCalibrator operates on PWM limit variable (using the iAmplifier->setPWMLimit) instead of modifying the output limit of the position PID. 
This solution is elegant and safer because the PWM limit globally affects all the controllers (position, torque etc). 
@barbalberto @valegagge : Do not merge this branch until the EMS fw has been tested (EMS2 and EMS4 must forward the set/get commands to the corresponding MC4 CAN boards). CAN boards should have fw build > 87 (can protocol 1.5)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/286%23issuecomment-217841507%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/286%23issuecomme …
> upgrade calibrator pwm limit

- app/robots/iCubHeidelberg01/calibrators/left_leg-calib.xml
- app/robots/iCubHeidelberg01/calibrators/right_leg-calib.xml
- app/robots/iCubHeidelberg01/calibrators/torso-calib.xml
- app/robots/iCubHeidelberg01/hardware/mechanicals/left_lower_leg-ems7-mec.xml
- app/robots/iCubHeidelberg01/hardware/mechanicals/left_upper_leg-ems6-mec.xml
- app/robots/iCubHeidelberg01/hardware/mechanicals/right_lower_leg-ems9-mec.xml
- app/robots/iCubHeidelberg01/hardware/mechanicals/right_upper_leg-ems8-mec.xml
- app/robots/iCubHeidelberg01/hardware/mechanicals/torso-ems5-mec.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/left_lower_leg-ems7-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/left_upper_leg-ems6-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/right_lower_leg-ems9-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/right_upper_leg-ems8-mc.xml
- app/robots/iCubHeidelberg01/hardware/motorControl/torso-ems5-mc.xml
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/hu-yue%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7060968%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/337%23issuecomment-217853209%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-09T12%3A40%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7060968%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/hu-yue%22%7D%7D%2C%20%7B%22body%22%3A%20%22Assuming%20you%27ve%20tested%20these%20modifications%20on%20the%20robot%2C%20I%27m%20going%20to%20merge%20th …
> Updated iCubHeidelberg configuration files

- app/robots/iCubDarmstadt01/calibrators/left_leg-calib.xml
- app/robots/iCubDarmstadt01/calibrators/right_leg-calib.xml
- app/robots/iCubDarmstadt01/calibrators/torso-calib.xml
- app/robots/iCubDarmstadt01/hardware/mechanicals/head-cfw2_can0-mec.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/left_lower_leg-ems7-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/right_lower_leg-ems9-mc.xml
- app/robots/iCubDarmstadt01/hardware/motorControl/torso-ems5-mc.xml
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/338%23issuecomment-219039656%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/338%23issuecomment-219039656%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40randaz81%20If%20you%20want%20to%20briefly%20check%2C%20otherwise%20we%20will%20merge.%22%2C%20%22created_at%22%3A%20%222016-05-13T13%3A16%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a …
> [iCubDarmstadt01] modifications after CoDyCoY3

- .travis.yml
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/342%23issuecomment-220538251%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/342%23issuecomment-220538251%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Travis%20on%20trusty%20working%20fine%2C%20merging.%20%22%2C%20%22created_at%22%3A%20%222016-05-20T07%3A36%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
> [travis] Migrate to trusty

- conf/FindIPOPT.cmake
Compatible with the version of IPOPT in the coinor-libipopt-dev deb package
Ref: robotology/robotology.github.io#3
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/344%23issuecomment-220546095%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/344%23issuecomment-220547078%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/344%23issuecomment-220546095%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40traversaro%20what%20was%20wrong%20with%20the%20other%202%20pr%3F%22%2C%20%22created_at%22%3A%20%222016-05-20T08%3A27%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3F …
> [cmake] Modified build system to find IPOPT from apt-get

- admin/scripts/README_RELEASE
If it is ok please merge @mbrunettini . 
For release 1.4.0 I updated the  http://wiki.icub.org/wiki/Downloads wiki page myself.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/mbrunettini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4234840%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/351%23issuecomment-225111924%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-10T07%3A25%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4234840%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mbrunettini%22%7D% …
> Add update of wiki pages of binaries in README_RELEASE

- src/libraries/icubmod/usbCamera/CMakeLists.txt
- src/libraries/icubmod/usbCamera/common/USBcamera.cpp
- src/libraries/icubmod/usbCamera/common/USBcamera.hpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/356%23issuecomment-230757092%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/356%23issuecomment-230757092%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22tested%20on%20CER01%20ok%22%2C%20%22created_at%22%3A%20%222016-07-06T12%3A28%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2869969%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/randaz81%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' …
> Usb camera resize

- app/robots/iCubGenova05/calibrators/head-calib.xml
- app/robots/iCubGenova05/calibrators/left_leg-calib.xml
- app/robots/iCubGenova05/calibrators/right_arm-calib.xml
- app/robots/iCubGenova05/calibrators/right_leg-calib.xml
- app/robots/iCubGenova05/calibrators/torso-calib.xml
Of legs, torso and head.
No fine calibration was performed of the arms,
except for the fix described in https://github.com/robotology/icub-support/issues/270 .
@randaz81 @davidetome can you check the modifications to the `calibration4`/`calibration5` parameters in `right_arm-calib.xml`? [1] 
I found these values on the robot .local and they seem to work well, but I don't know if they are correct or not. 
[1] :  https://github.com/robotology/icub-main/pull/357/files#diff-45e7af6bc262b6df0746365be8d6b9f2L24
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/357%23issuecomment-232349601%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/357%23issuecomment-232357848%22%2C%20%22https%3A//github.com/robotology/icub-main …
> [iCubGenova05] Fine calibration

- app/robots/iCubGenova02/calibrators/head-calib.xml
- app/robots/iCubGenova02/calibrators/left_leg-calib.xml
- app/robots/iCubGenova02/calibrators/right_leg-calib.xml
- app/robots/iCubGenova02/calibrators/torso-calib.xml
See http://wiki.icub.org/wiki/File:Fine_calibration.xls
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/364%23issuecomment-243176702%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/364%23issuecomment-243178849%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/364%23issuecomment-243176702%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Yeshasvitvs%20%40francesco-romano%20%40traversaro%20%5Cr%5CnWhat%20shall%20we%20do%20with%20this%20PR%3F%20Is%20it%20mergeable%3F%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-29T16%3A30%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.co …
> [Calibrators] Fine calibration done for the Legs/Torso/Head

- app/robots/iCubLisboa01/iCubStartup.xml
> [iCubLisboa01]: change iKinGazeCtrl minimum eye tilt angle

- app/robots/iCubLisboa01/affordancesExploration.xml
- app/robots/iCubLisboa01/camera/dragonfly2_config_left_bayer_640_480.ini
- app/robots/iCubLisboa01/camera/dragonfly2_config_right_bayer_640_480.ini
- app/robots/iCubLisboa01/cameras_320x240_setForTracking.xml
- app/robots/iCubLisboa01/cameras_calib_bayer_640x480.xml
- app/robots/iCubLisboa01/demoRedBall.xml
- app/robots/iCubLisboa01/dynamicBabbling.xml
- app/robots/iCubLisboa01/dynamicControl.xml
- app/robots/iCubLisboa01/iCubGui.xml
- app/robots/iCubLisboa01/iCubGui_skinContacts.xml
and other misc script improvements (module names, whitespace, etc.)
> [iCubLisboa01]: fix 640x480 images

- .travis.yml
We should pay attention to this when merging `devel` to `master` for a release.
cc @drdanz @pattacini
> [travis] On devel branch, get yarp devel

- src/tools/depth2kin/include/module.h
- src/tools/depth2kin/src/module.cpp
Implements what discussed in https://github.com/robotology/QA/issues/152 about using analog sensors.
> Improve depth2kin localization of finger tips using analogs

- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
This is a quick fix for what it looks like a memory problem ... to be further investigated
> Fix random crash into ParametricCalibrator

- CMakeLists.txt
- conf/iCubExportForInstall.cmake
- conf/template/icub-config-install.cmake.in
Trying to fix issue [#199](https://github.com/robotology/icub-main/issues/199#issue).
> trying to fix issue #199 [icub-main]

- src/libraries/icubmod/usbCamera/common/USBcamera.cpp
- src/libraries/icubmod/usbCamera/common/USBcamera.hpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
- src/libraries/icubmod/usbCamera/linux/V4L_camera.hpp
> V4L_camera: added the inheritance from yarp::dev::IRgbVisualParams and implemented the relative virtual methods.

- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.cpp
- src/libraries/icubmod/parametricCalibrator/parametricCalibrator.h
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.h
Always verify joint to calibrate is valid.
This ckech does not assume joints are all consequential.
Tested on black iCub
> ParametricCalibrator: add check joints are in range in calibrator devices

- src/libraries/icubmod/usbCamera/linux/V4L_camera.cpp
Few changes to usbCamera driver for Linux to comply with new firmware from producers.
Tested ok
> Updated usb camera python

- src/libraries/skinDynLib/include/iCub/skinDynLib/common.h
- src/libraries/skinDynLib/include/iCub/skinDynLib/dynContactList.h
- src/libraries/skinDynLib/include/iCub/skinDynLib/rpcSkinManager.h
- src/libraries/skinDynLib/src/common.cpp
- src/libraries/skinDynLib/src/skinContact.cpp
- src/modules/skinManager/include/iCub/skinManager/compensationThread.h
- src/modules/skinManager/include/iCub/skinManager/compensator.h
- src/modules/skinManager/include/iCub/skinManager/skinManager.h
- src/modules/skinManager/src/compensationThread.cpp
- src/modules/skinManager/src/compensator.cpp
- src/modules/skinManager/src/skinManager.cpp
With @fjandrad and @joankangro we plan to use (and possibly extent) the skinDynLib library and the skinManager module, but at the moment there were some style issues that prevented to even read the code efficently on GitHub. In this PR I fixed some of this issues. 
* https://github.com/traversaro/icub-main/commit/feb5b36d9d32898f4f579b4fee53ade3fd5df93a - Remove some dead code from skinDynLib 
* https://github.com/traversaro/icub-main/commit/b144aa572eb51d22d02521a765edc8e1129cdbee - Cleanup tabs and spaces mismatch
* https://github.com/traversaro/icub-main/commit/6cf97c3d6a4acda4b5ea7130985f211c8dc569b7 - Cleanup tabs and spaces mismatch
I propose to merge this (non-functional) changes in the `master` branch to avoid crazy conflicts in the future if we want to fix some bugs in `master` …
> Cleanup of skin-related software

- src/libraries/ctrlLib/include/iCub/ctrl/filters.h
Fixes https://github.com/robotology/icub-main/issues/463
@pattacini @traversaro
> New IFilter interface

- src/tools/iCubGui/src/objectsthread.h
Fix https://github.com/robotology/icub-main/issues/467
> [iCubGui] Fix crash for malformed skinContact

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
- src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
removed variable length arrays which are not c++ standard.
> removed variable length array which are not c++ standard.

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
Solve issue robotology/icub-support#611.
It has already been tested on robot
> fixed EOMC::setControlModesraw(three params)

- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
> embobjmotioncontrol: added remote variables to display the pid in raw format

- src/libraries/iKin/src/iKinFwd.cpp
This PR adds support for ring and little fingers within `iCub::iKin::iCubFinger` Class.
> Implement ring and little fingers within iCub::iKin::iCubFinger Class

- src/libraries/icubmod/canBusSkin/CanBusSkin.cpp
- src/libraries/learningMachine/src/Serialization.cpp
- src/modules/motionCUT/main.cpp
- src/tools/depth2kin/src/module.cpp
Merge after robotology/yarp#1710
> [WIP] Fixes after sizet correction in YARP

- src/libraries/iDyn/src/iDyn.cpp
- src/libraries/iDyn/src/iDynBody.cpp
- src/libraries/iDyn/src/iDynInv.cpp
- src/libraries/iKin/include/iCub/iKin/iKinSlv.h
- src/libraries/iKin/src/iKinSlv.cpp
- src/modules/iKinGazeCtrl/src/utils.cpp
Fixes after robotology/yarp#1716
> Fix sizet bottle

- CMakeLists.txt
- src/doc/release/v1_11_0.md
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.cpp
- src/libraries/icubmod/embObjLib/CMakeLists.txt
- src/libraries/icubmod/embObjMotionControl/eomcParser.h
- src/libraries/icubmod/embObjVirtualAnalogSensor/embObjVirtualAnalogSensor.cpp
- src/libraries/icubmod/esdSniffer/EsdMessageSniffer.cpp
- src/libraries/learningMachine/include/iCub/learningMachine/DatasetRecorder.h
- src/libraries/learningMachine/include/iCub/learningMachine/DummyLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/IFixedSizeLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/IFixedSizeTransformer.h
- src/libraries/learningMachine/include/iCub/learningMachine/IMachineLearner.h
- src/libraries/learningMachine/include/iCub/learningMachine/ITransformer.h
- src/libraries/learningMachine/include/iCub/learningMachine/PortableT.h
- src/libraries/learningMachine/include/iCub/learningMachine/Prediction.h
- src/libraries/learningMachine/include/iCub/learningMachine/RandomFeature.h
- src/libraries/learningMachine/src/DatasetRecorder.cpp
- src/libraries/learningMachine/src/DummyLearner.cpp
- src/libraries/learningMachine/src/IFixedSizeLearner.cpp
- src/libraries/learningMachine/src/IFixedSizeTransformer.cpp
- src/libraries/learningMachine/src/RandomFeature.cpp
- src/libraries/skinDynLib/include/iCub/skinDynLib/dynContact.h
- src/libraries/skinDynLib/include/iCub/skinDynLib/dynContactList.h
- src/libraries/skinDynLib/include/iCub/skinDynLib/skinContact.h
- src/libraries/skinDynLib/include/iCub/skinDynLib/skinContactList.h
- src/libraries/skinDynLib/src/dynContact.cpp
- src/libraries/skinDynLib/src/dynContactList.cpp
- src/libraries/skinDynLib/src/skinContact.cpp
- src/libraries/skinDynLib/src/skinContactList.cpp
- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
This PR fixes devel branch after the release of YARP 3.0.0
cc @traversaro
> Fix devel branch after YARP 3.0.0 release

- .gitignore
- CMakeLists.txt
- bindings/CMakeLists.txt
This PR should fix and clean icub bindings, it is incomplete, feel free to complete it and merge it when it is ready
> [WIP] Fix bindings

- src/libraries/iKin/include/iCub/iKin/iKinFwd.h
- src/libraries/iKin/src/iKinFwd.cpp
- src/libraries/iKin/src/iKinSlv.cpp
- src/modules/iKinGazeCtrl/include/iCub/utils.h
- src/modules/iKinGazeCtrl/src/controller.cpp
- src/modules/iKinGazeCtrl/src/main.cpp
- src/modules/iKinGazeCtrl/src/solver.cpp
- src/modules/iKinGazeCtrl/src/utils.cpp
This PR addresses the need for handling the iCub v3 torso kinematics correctly.
@ale-git please give it a look.
> Fix for iCub v3 torso kinematics

- src/tools/frameGrabberGui2-qt/mainwindow.cpp
This PR fixes #565 
please review code
> FGGUI2: fix segfault caused by out of index

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.h
This PR extends the park routine of ParametricCalibratorEth to perform a sequence of movements when shutting down the robot.
Test on robot R1 successful
> Parking sequence feature upgrade

- src/libraries/icubmod/parametricCalibratorEth/parametricCalibratorEth.cpp
fix error in loading startup position from HOME group
> parametric calibrator eth: bug fix due to new parking procedure

- src/core/emotionInterface/emotionInterfaceModule.cpp
- src/core/emotionInterface/emotionInterfaceModule.h
- src/modules/camCalibWithPose/include/iCub/CamCalibModule.h
- src/modules/camCalibWithPose/src/CamCalibModule.cpp
- src/tools/stereoCalib/include/stereoCalibThread.h
- src/tools/stereoCalib/src/stereoCalibThread.cpp
> Use std::mutex and std::condition_variable (2)

- src/libraries/iCubDev/include/iCub/LoggerInterfaces.h
- src/libraries/skinDynLib/include/iCub/skinDynLib/skinPart.h
- src/libraries/skinDynLib/src/skinPart.cpp
- src/modules/skinManager/include/iCub/skinManager/compensationThread.h
- src/modules/skinManager/include/iCub/skinManager/compensator.h
- src/modules/skinManager/src/compensationThread.cpp
- src/modules/skinManager/src/compensator.cpp
- src/tools/iCubSkinGui-gtk/src/SkinMeshThreadCan.cpp
- src/tools/iCubSkinGui-gtk/src/SkinMeshThreadPort.cpp
- src/tools/iCubSkinGui-gtk/src/include/SkinMeshThreadCan.h
- src/tools/iCubSkinGui-gtk/src/include/SkinMeshThreadPort.h
- src/tools/iCubSkinGui-gtk/src/main.cpp
- src/tools/iCubSkinGui-qt/plugin/SkinMeshThreadCan.cpp
- src/tools/iCubSkinGui-qt/plugin/SkinMeshThreadPort.cpp
- src/tools/iCubSkinGui-qt/plugin/include/SkinMeshThreadCan.h
- src/tools/iCubSkinGui-qt/plugin/include/SkinMeshThreadPort.h
- src/tools/iCubSkinGui-qt/plugin/qticubskinguiplugin.cpp
- src/tools/skinManagerGui-gtk/include/iCub/skinManagerGui/guiCallback.h
- src/tools/skinManagerGui-gtk/include/iCub/skinManagerGui/main.h
- src/tools/skinManagerGui-qt/mainwindow.h
- src/tools/skinManagerGui-qt/portthread.h
All along with #612 #613 #614 #615.
> Skin uses std::mutex + std::condition_variable

- src/libraries/icubmod/bcbBattery/bcbBattery.cpp
- src/libraries/icubmod/bcbBattery/bcbBattery.h
- src/libraries/icubmod/bmsBattery/bmsBattery.cpp
- src/libraries/icubmod/bmsBattery/bmsBattery.h
- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.cpp
- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.h
- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.cpp
- src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.h
- src/libraries/icubmod/dragonfly2/winnt/FirewireCameraDC1394-DR2_2.h
- src/libraries/icubmod/imu3DM_GX3/3dm_gx3.cpp
- src/libraries/icubmod/imu3DM_GX3/3dm_gx3.h
- src/libraries/icubmod/imuST_M1/ST_M1.cpp
- src/libraries/icubmod/imuST_M1/ST_M1.h
- src/libraries/icubmod/skinprototype/skinprototype.cpp
- src/libraries/icubmod/skinprototype/skinprototype.h
- src/libraries/icubmod/xsensmtx/XSensMTx.cpp
All along with #612 #613 #614 #615 #616.
> Mutex cleanup (3)

- src/libraries/icubmod/embObjLib/ethResource.cpp
- src/modules/iKinGazeCtrl/include/iCub/gazeNlp.h
cleaned some compilation warning: string too small in snprintf(), missing return value in function.
> cleaned some compilation warning

- src/modules/positionDirectControl/main.cpp
- src/modules/velocityControl/main.cpp
small cleanup to remove compilation warnings + used snprintf() instead of sprintf() to avoid write out of mem
> fixed compilation warning + potential write out of memory

- src/tools/iCubGui/src/visionobj.h
It adresses https://github.com/icub-tech-iit/task-force-miscellanea/issues/25
> Fix iCubGui red ball, it is now actually a ball

- .github/workflows/ci.yml
- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/canBusInertialMTB/CMakeLists.txt
- src/libraries/icubmod/canBusSkin/CMakeLists.txt
- src/libraries/icubmod/embObjLib/FeatureInterface.cpp
- src/libraries/icubmod/embObjLib/FeatureInterface.h
- src/libraries/icubmod/embObjLib/ethManager.cpp
- src/tools/FirmwareUpdater/CMakeLists.txt
- src/tools/canLoader/canLoader-console/CMakeLists.txt
This PR aims to fix https://github.com/robotology/robotology-superbuild/issues/372
The functionality has to be tested, the compilation has been tested only on linux.
Linked to https://github.com/robotology/icub-firmware-shared/pull/36
> Fix linking issues win32 after the porting to modern icub-firmware-shared

- src/simulators/iCubSimulation/wrapper/iCubSimulationControl.cpp
icubSimulationControl: fixed check on joint limits when a position command is received.
> Fix on icubSIM joint limits

- app/faceExpressions/doc.dox
Fix documentation for the command of changing the color in the face expressions
cc @julijenv @Iaxama
> FaceExpressions: update doc.dox

- src/tools/FirmwareUpdater/main.cpp
see https://github.com/robotology/icub-main/issues/704
> fixed bug in duplicated command line options 

- src/CMakeLists.txt
> Don't build simulator on APPLE by default

- src/libraries/iKin/src/iKinFwd.cpp
- src/modules/iKinGazeCtrl/src/main.cpp
This PR introduces version 2.8 of the kinematics of the head EDPR.
> iCub::iKin::iCubEye 2.8

- .ci/packages_vars.sh
> Update script for generating the deb packets for using ycm 0.13.0

- .ci/create_icub-main_deb.sh
- .ci/packages_vars.sh
- .github/workflows/packages_creation.yml
As per title.
Putting as draft until we do not have the packages of YARP and YCM
> Packages creation: update script for 2022.05.0 release

- src/libraries/icubmod/embObjBattery/README.md
- src/libraries/icubmod/embObjBattery/embObjBattery.cpp
- src/unittest/testDeviceCanBatterySensor.cpp
Fix voltage truncation to the first decimal.
Fix documentation about debugging.
> fix voltage truncation and add some doc

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/tools/canLoader/canLoaderLib/downloader.cpp
This PR adds support for `mtb4c` boards
---
⚠️ Blocked by:
- https://github.com/robotology/icub-firmware-shared/pull/65
cc @marcoaccame @pattacini
> adding support for mtb4c

- src/libraries/icubmod/embObjFTsensor/embObjFTsensor.cpp
- src/libraries/icubmod/embObjFTsensor/eo_ftsens_privData.cpp
- src/libraries/icubmod/embObjFTsensor/eo_ftsens_privData.h
- src/libraries/icubmod/embObjLib/serviceParser.cpp
- src/libraries/icubmod/embObjLib/serviceParser.h
Added framename for single FT sensor device
> Framename single ft fix

- src/unittest/testDeviceMultipleFTSensors.cpp
fix test for new temperature management
> Fix Temperature Management in CI/Tests

- .github/workflows/ci.yml
> [ci] streamline

- src/libraries/icubmod/embObjBattery/README.md
some documentation fix thanks to @S-Dafarra
> fix documentation

- src/libraries/iKin/src/iKinFwd.cpp
- src/modules/iKinGazeCtrl/src/main.cpp
Follow-up on #837.
cc @mfussi66 
However, there's a major flaw we need to address in versioning as v2.10 == v2.1.
I'll be on that.
> Add icub v3.1

- .github/workflows/ci.yml
- src/libraries/icubmod/bcbBattery/bcbBattery.h
- src/libraries/icubmod/bmsBattery/bmsBattery.h
- src/libraries/icubmod/canBusMotionControl/CanBusMotionControl.h
- src/libraries/icubmod/dragonfly2/common/DragonflyDeviceDriver2.h
- src/libraries/icubmod/imu3DM_GX3/3dm_gx3.h
- src/libraries/icubmod/imuST_M1/ST_M1.h
- src/libraries/icubmod/skinWrapper/skinWrapper.h
- src/libraries/icubmod/xsensmtx/XSensMTx.h
- src/tools/iCubGui/src/bvh.h
Updates induced by https://github.com/robotology/yarp/pull/2893.
> Fixed deprecated headers

- .github/workflows/ci.yml
Ths fallback are `master` and `devel` with `icub-main@master` and `icub-main@devel`, respectively.
> Try to clone the required version of `icub-firmware-shared` when possible

- .github/workflows/ci.yml
`unzip` installed via `choco` is somehow problematic.
Switched to the use of `7zip`.
> [CI] fixing `choco`

- app/skinGui/conf/skinGui/left_hand_V2_2.ini
- app/skinGui/conf/skinGui/right_hand_V2_2.ini
- src/tools/iCubSkinGui/plugin/Fingertip3Left.cpp
- src/tools/iCubSkinGui/plugin/Fingertip3Right.cpp
- src/tools/iCubSkinGui/plugin/include/Fingertip3Left.h
- src/tools/iCubSkinGui/plugin/include/Fingertip3Right.h
- src/tools/iCubSkinGui/plugin/include/SkinMeshThreadCan.h
- src/tools/iCubSkinGui/plugin/include/SkinMeshThreadPort.h
Added files for generating the skin GUI for mk1.1 fingertip aka FT2L/R with the revised taxel positions
> Fingertip mk1.1 skinGui

- src/libraries/icubmod/dragonfly2/CMakeLists.txt
> Change dragonfly2 wrapper from grabberDual to frameGrabber_nws_yarp

- app/wholeBodyPlayer/scripts/wholeBodyPlayer_App.xml.template
> WholeBodyPlayer: remove iCub_SIM leftover

- app/wholeBodyDynamics/scripts/wholeBodyDynamics.xml.template
- app/wholeBodyDynamics/scripts/wholeBodyDynamics_no_legs.xml.template
- src/modules/wholeBodyDynamics/main.cpp
- src/modules/wholeBodyDynamics/observerThread.cpp
- src/modules/wholeBodyDynamics/observerThread.h
It fixes #865 
x-ref: #596 
TO BE TESTED!
> wbd: port it for using MAS client also for FT 

- src/modules/wholeBodyDynamics/main.cpp
This regression has been added in #876
> wbd: fix dummy_ft options after refactoring

- src/libraries/icubmod/embObjMais/embObjMais.cpp
- src/libraries/icubmod/embObjMais/embObjMais.h
It fixes #851.
Not sure if this implementation makes sense @marcoaccame @traversaro.
If it is ok I will test it on `iCubGenova11`
> embObjMais: expose data via MAS interface

- src/libraries/icubmod/imuFilter/ImuFilter.h
- src/libraries/icubmod/imuFilter/PassThroughInertial.cpp
- src/libraries/perceptiveModels/include/iCub/perception/sensors.h
- src/libraries/perceptiveModels/include/iCub/perception/springyFingers.h
- src/libraries/perceptiveModels/src/sensors.cpp
- src/libraries/perceptiveModels/src/springyFingers.cpp
- src/modules/wholeBodyDynamics/main.cpp
- src/modules/wholeBodyDynamics/observerThread.h
- src/tools/depth2kin/include/module.h
- src/tools/depth2kin/src/module.cpp
This PR addresses #908 taking into account the mods proposed via https://github.com/robotology/robots-configuration/pull/568.
In particular, two components are updated:
- The module `depth2kin`
- The library `perceptiveModels`
> Update MAIS reading modules to use MAS

- src/modules/camCalib/src/CamCalibModule.cpp
- src/modules/camCalibWithPose/src/CamCalibModule.cpp
- src/modules/dualCamCalib/src/DualCamCalibModule.cpp
- src/modules/skinManager/include/iCub/skinManager/compensator.h
- src/modules/skinManager/src/compensator.cpp
> fixed issue with yarp 3.10

- src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp
This PR fixes the programming result of ETH boards (#939 )
cc @valegagge
> FirmwareUpdater - fix programming ETH board result and message

- src/core/emotionInterface/emotionInterfaceModule.cpp
This is a bug reported by the community:
- https://github.com/orgs/robotology/discussions/694
> Fix emotion interface set mask command

- src/modules/actionsRenderingEngine/src/pointing_far.cpp
This PR improves the `pfar` ARE command by fiddling with the constraints bounds, essentially.
cc @martinaxgloria @Nicogene
> Improve ARE Pointing Far (aka `pfar`) capability

- src/modules/actionsRenderingEngine/src/pointing_far.cpp
This patch allows ARE to use `pfar` also for close objects preventing the arm from touching them.
cc @Nicogene @martinaxgloria
> Improve `ARE::pfar` for near objects

- src/libraries/perceptiveModels/include/iCub/perception/sensors.h
- src/libraries/perceptiveModels/src/sensors.cpp
- src/modules/actionsRenderingEngine/src/MotorThread.cpp
> Fix fingers calibration in ARE

- conf/iCubFindDependencies.cmake
- src/libraries/icubmod/embObjLib/diagnosticInfoParsers.cpp
- src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
Update amo diagnostic errors in the parser
Fix error in masking the values in the diagnostic parser
> Update diagnostic message i2c not communicating

- conf/iCubFindDependencies.cmake
> Bumped correct version of `icub-fw-shared`

- .github/workflows/ci.yml
As per the title.
cc @randaz81 @Nicogene @traversaro
> CI use YARP tags instead of branches

- src/libraries/icubmod/fineCalibrationChecker/src/FineCalibrationChecker.cpp
- src/libraries/icubmod/fineCalibrationChecker/src/FineCalibrationChecker.h
As per title.
See:
- https://github.com/robotology/robots-configuration/pull/748#issuecomment-3140623195
> fineCalibrationChecker: add withGui parameter
